heimdal/heimdal

lib/kadm5/Makefile.am
When running `make` with `-j4`, occasionally kadm5 fails due to a missing header file `kadm5_err.h`. Fix the race condition.
Thanks @jcajka for the original patch.
This is a cherry-pick of commit 6affa4cceceaa1369dd895f8acdd7a883ee65674 which was merged to master in https://github.com/heimdal/heimdal/pull/108 . This pull request is for the 1.6 branch.
=> kadm5: fix race in Makefile with kadm5_err.h

lib/krb5/addr_families.c
I'm not sure if this is still needed? @net9rok had added this to the Fedora packages in July 2012, and I want to send this upstream to see if we still need it or if I should drop it from the Fedora/EPEL packages.
"Fix IPv6 and multiple interfaces bug in krb5_parse_address." See discussion at https://bugzilla.redhat.com/808147
=> ipv6 loopbacks fix

cf/crypto.m4, include/NTMakefile, include/config.h.w32, lib/hcrypto/rand-fortuna.c, lib/hcrypto/test_rand.c, lib/krb5/crypto-rand.c, windows/NTMakefile.config
Hi,
Current 1.5.3 heimdal does not build with LibreSSL as it does not have EGD support. This fixing and upstreaming is part of the work done to enable all ports to work with LibreSSL on FreeBSD, see https://wiki.freebsd.org/LibreSSL and the PR to fix this is https://bugs.freebsd.org/198527
I believe it is safe to remove EGD altogether as this is a relic from the past, nothing recent requires EGD (not even Windows as can be seen in the master branch).
Latest versions requiring EGD
IRIX 6.5.19 Feb 2003
Solaris 2.6 Jul 1997
AIX 5.2 Oct 2002
Tru64 5.1B Sep 2002
HP-UX 11i v2 Sep 2003
This patch detects EGD support in the OpenSSL (or LibreSSL) libcrypto and adds ifdef's where relevant. Looks a bit kludgy now that this has been made conditional in the reverse way for Windows.
Hope you will add …
=> Fix build when OpenSSL has no EGD support

lib/roken/dlfcn.hin
When dlfcn.h is included from a C++ file causes a compilation error due to missing '{'.
=> Fix compilation error in dlfcn.h

lib/hx509/hx509_err.et, lib/hx509/ks_p11.c
This PR add:
* more support related to common PIN errors (PIN blocked, incorrect, ...)
* the corresponding messages allowing a more friendly debugging.
* fix a small typo
* allow more than one token to be present (if the first is not usable, the second one can be).
Credit: thanks to Romain Sahut for his help.
=> PK-INIT improvements

lib/gssapi/krb5/accept_sec_context.c
Some non-GSSAPI implementations that instead try to create compatible packets by wrapping krb5_mk_req()
can trigger a NULL authenticator here.  Assume this to be equvilent to specifying an all-zero
channel bindings and some reasonable (fixed) flags.
Andrew Bartlett
=> gssapi: Allow a NULL authenticator

lib/hx509/crypto.c, lib/hx509/ks_p11.c
Example usage: kinit -C PKCS11:/usr/lib/opensc-pkcs11.so,slot=3 foo@BAR.TLD
This is required for certain tokens, such as the OpenPGP cards, that default to an incorrect slot.  Slot numbering is consistent with the pkcs11 PAM module.
=> Add ability to specifiy PKCS#11 slot number when using hx509

lib/hdb/hdb-ldap.c, lib/hdb/hdb.schema
When attempting to deploy PKI infrastructure on our Kerbeos servers with LDAP backends it was discovered that the Heimdal Kerbeos extended attribute structure (including PKI mapping fields) was not supported with the LDAP backend.  This patch fixes this critical issue.
Original commit text:
A careful code review was undertaken, and it was determined
that the best way to store the extended attributes was in a
native ASN1 encoded field.  LDAP does not understand the
SEQUENCE of SEQUENCE structures used extensively throughout
the extended attributes structure, and there was already a
precedent set for storing the krb5Key data in a native ASN1
encoded field.
=> Add ability to store extended principal attributes in LDAP

lib/krb5/pac.c
ucs2 was already NULL checked earlier, this is never reached (and is doing a free(NULL), which man free(3) says it's a no-op) so no worries there.
You actually want to NULL-check s2 who has just received a malloc() result.
=> lib/krb5/pac.c: fix NULL check typo

lib/gssapi/mech/gss_compare_name.c
Make memcmp() compare the name1 and name2 value instead of comparing
name1 with itself.
The memcmp() is only executed if the left-hand side of the || is false
i.e. when both length are equal so the length argument is correct (no out-of-bounds reads).
I'm confused about the `$FreeBSD: ...$` tag, is this originally from FreeBSD SVN? Should I send this change on their mailing list?
=> lib/gssapi/mech/gss_compare_name.c: fix memcmp() call

lib/krb5/krb5.conf.5
Fix grammar at multiple places
Also, fix mdoc syntax at one place. There should be a space between the
section and the comma in the .Xr macro.
=> Various fixes in kfb5.conf man page:

kdc/Makefile.am
This is an improvement on https://github.com/heimdal/heimdal/pull/153, which didn't enforce that kdc-protos.h was build before string2key.o.
The original Makefile.am already supported parallel builds, it just had a typo in it.
=> Fix parallel builds.

include/bits.c
Including HOST causes the build to be unreproducible.
See also https://tests.reproducible-builds.org/rb-pkg/testing/i386/heimdal.html
=> Don't put system architecture in generated headers.

kdc/krb5tgs.c
This reverts commit 1124c4872dfb81bec9c4b527b8927ca35e39a599.
A reason for deviation from RFC4120 is backward compatibility.
With Windows RODC's, it is likely to have a kvno for the tgt which
has bit 31 set. Encoding such a kvno as unsigned would lead to a
5-byte number, whereas Windows, which treats kvno as int32, expects
up to 4 bytes. MIT Kerberos does the same for the exact same reason.
The encoding has already been reverted in commit
060474df1626bcc597ef6e786cc58d9b2daac8db. After reverting the encoding,
there's no reason to use krb5uint32 in the context of kvno, so this
commit reverts the rest, plus removes one more use of krb5uint32 in
the context of kvno.
Signed-off-by: Uri Simchoni <uri@samba.org>
=> Revert "KVNOs are krb5uint32 in RFC4120, make it so"

lib/hx509/version-script.map, lib/roken/version-script.map
Commit efed5633 (r24759) prefixed some symbols with rk_, but introduced 6 duplicate symbols in the version script (because the rk_-prefixed versions of the symbols were already present).
=> Remove duplicate symbols from libroken version-script.map

configure.ac, kuser/Makefile.am, lib/Makefile.am
The --disable-afs-support configure flag doesn't really disable afs. It still gets built, and kinit still links to it, although it doesn't use it.
=> --disable-afs-support doesn't really disable afs

lib/hcrypto/evp.c, lib/hcrypto/test_bulk.c, lib/hcrypto/test_cipher.c
This caused undefined symbol errors on multiple platforms. I can't remember which. Seems like it was x86 solaris and ia64 hpux.
gcc 4.6.1
=> The evp-w32.h header should not be included on all platforms

configure.ac
My fix in d8080162eab578337de08637faed39106efdc557 turns off AFS all the time. @nicowilliams fix in 6d1571a3c4e4f126e6527b00e2ee7cf5b22b7b11 leaves AFS on always.
This is the proper way to define the AM_CONDITIONAL. I tested this with and without the --disable-afs-support flag, and it now behaves correctly.
=> Properly define the NO_AFS AM_CONDITIONAL

lib/hcrypto/rand-fortuna.c
`__GNUC__` was written as `__GUNC__`, which could have interesting results as it'll never be defined.
=> Fix typo in rand-fortuna.c

lib/krb5/context.c, lib/krb5/krb5_locl.h
When sending a TGS request as part of GSSAPI client-side
context negotiation, use for etypes the value in the
credentials, and if that's not set - the values in the
configuration.
When the krb5 context is created, and krb5.conf is read, the allowed enctyption types are set to whatever is in krb5.conf (or the full set as default). Then, without this patch, if no enc types are associated with the credentials, the enc types are reset to the full set. This would not allow limiting the encryption types via configuration.
It seems like the current code is intentional. I was just unable to figure out the intent (I get the part of overriding the etypes with the stuff in the credentials, but not the part of resetting to default). Therefore I'm sending over this pull request - to be accepted or …
=> Honor krb5.conf-configured etypes for GSSAPI TGS request

kdc/krb5tgs.c
When processing a request, current tgs_make_reply uses the requested
set of addrs of the request to establish the set of addresses to
associate with the ticket in reply.
However, when the request input set of addrs is NULL, it reverts to
using the TGT set of addresses instead. As a result, it is not
possible to acquire an addressless TGS (or forwarded TGT) using a
TGT that is addressed.
This patch remove the fallback ensuring that a TGS_REQ with a set
of addrs set to NULL enables to acquire an addressless ticket.
=> krb5tgs: let TGS_REQ with NULL caddr returns an addessless ticket

cf/db.m4, lib/hdb/db.c, lib/otp/Makefile.am
On my FreeBSD system I have the folowing Berkeley DB
packages installed:
db41-4.1.25_4                  The Berkeley DB package, revision 4.1
db42-4.2.52_5                  The Berkeley DB package, revision 4.2
db48-4.8.30.0_2                Berkeley DB package, revision 4.8
db5-5.3.28_4                   Oracle Berkeley DB, revision 5.3
The last one has uses /usr/local/lib/libdb-5.so naming
scheme, unlike the previous version.
DB1-compatible interface also gets detected, so HAVE_DB1
and HAVE_DB3 also get defined, leading to conflicting symbols.
=> [WIP] HAVE_DB3 and HAVE_DB1 conflict when both defined

lib/roken/resolve.c
In lib/roken/resolve.c, we find rk_dns_srv_order() which re-orders
the results of an SRV RR lookup by the algorithm in RFC2782.  We
fix a bias in the random weight sorting by changing the order of
operations when selecting rnd.  rnd should be a non-zero random
number less than the sum of the weights at a particular priority,
but zero was included as a legitimate output thus biasing the
selection process.  rk_random() % sum is still biased as a 32
bit int modulo a number which doesn't divide 2^32 does not have
a uniform distribution, but the bias should be small enough to
live with for our purposes here.
=> Fix bias in ordering SRV RR results by weight.

tools/heimdal-gssapi.pc.in
This fixes the library path on e.g. systems like Debian which specify a custom --includedir and --libdir to configure.
=> Use actual libdir/includedir in heimdal-gssapi.pc.

tests/kdc/wait-kdc.sh
This is required when running on slower platforms. In Debian, we're hitting the timeout building on mips.
=> Increase timeout when waiting for iprop-slave.

lib/hcrypto/libtommath/tommath.h
Fixes test failures due to ISO C Undefined Behaviour in MP_MASK macro.
Thorsten is also forwarding this to upstream libtommath.
=> Do not detect x32 as 64-bit platform.

lib/hdb/keys.c, lib/hdb/test_hdbkeys.c, lib/hdb/version-script.map, lib/kadm5/set_keys.c
The change to the signature of hdb_generate_key_set_password() in
Heimdal 7.1 broke API/ABI compatibility with previous releases.  We
fix this by renaming it hdb_generate_key_set_password_with_ks_tuple()
and creating a new hdb_generate_key_set_password() which calls our
new function with zeroes for the added arguments.
Issue #246      https://github.com/heimdal/heimdal/issues/246
=> Fix signature of hdb_generate_key_set_password()

lib/ipc/common.c
Since pthread_cond_t is undefined, if I disable pthread with --disable-pthread-support, it should try to create this struct. It isn't used anyway, since the only place it's used is inside a #if ENABLE_PTHREAD_SUPPORT block.
I think this was on hpux pa 11.11 with gcc 4.7.1.
=> On hpux, pthread_cond_t is undefined when pthread is disabled

kdc/connect.c
In de_http() treat any sequence of '%' not followed by two hex digits
as invalid.
Change-Id: I812665c1a2806f8daba06d267bbee57287aa2314
=> kdc: de_http stricter parsing

tests/kdc/check-iprop.in
The output of `wc -l` includes leading white-space, and at least
in FreeBSD 11, `expr 1 + "$foo"` fails when "$foo" (captured as
`wc -l` output) has leading whitespace.  Instead, just emit one
more line for "wc" to count.
=> Avoid expr in non-portable comparison

lib/krb5/config_file.c
If the file is not a regular file, the 'fname' buffer will be freed
before it is passed to the krb5_set_error_message() routine.  That
this is true is not obvious from code inspection but 'newfname'
and 'fname' refer to the same memory.
Change-Id: I7780eae9ceaf01b245df488a2f7d7f406770864f
=> lib/krb5: krb5_config_parse_file_multi use after free

configure.ac, lib/roken/Makefile.am, lib/roken/issuid.c, lib/roken/roken.h.in, lib/roken/test-auxval.c, lib/roken/version-script.map
This set of changes will make issuid() much more likely to return the correct answer on:
- Linux with old glibc
- FreeBSD
- NetBSD
and should continue to return the correct answer on:
- Linux with newer glibc
- Illumos
- OpenBSD
=> Further improvements to issuid()

tests/kdc/check-iprop.in
Creation of a random key HDB entry takes 3 updates, not one.  Instead of
hard-coding this magic count, wait for the appearance of the expected
entry with no "invalid" flag among its attributes.
=> Fix check-iprop race

tests/kdc/check-iprop.in
Though a race was never observed, the re-sync, slave DB deletion,
master changes and restart did not take into account late changes
in the master before slave down.
=> Avoid another potential check-iprop race.

lib/krb5/keytab.c
=> krb5_kt_next_entry() needs to operate on a zero'd krb5_keytab_entry.

lib/gssapi/ntlm/release_cred.c
ntlm_cred is always allocated with calloc, so we need to free the cred
object too, similarly to what _gsskrb5_release_cred does.
=> Fix memory leak in _gss_ntlm_release_cred.

kdc/krb5tgs.c
(cherry picked from commit 3910c23378e56f35dc23a94fdc331cf64a025329)
=> Retain `ret != 0` when capaths finds no match.

lib/libedit/src/vis.h
Fix for issue #294, correctly wrap include of sys/cdefs.h to only fire when it is available.
=> Fixes https://github.com/heimdal/heimdal/issues/294

kdc/connect.c
When the termination of a child process is observed by reap_kid() it
clears the pids[] element by assigning it the invalid pid value
(pid_t)-1. However, start_kdc() assumes that the unused pid[[] element
value is 0.  As a result, each pid[] element's associated child process
can only be restarted once since start_kdc() will not be able to locate
an unused element.
This change alters start_kdc() to initialize all elements of pids[] to
(pid_t)-1 and use that as the marker for unused elements.  By doing so
start_kdc() can properly record child process pids and indefinitely
restart child processes as necessary.
Change-Id: Ia93c9284ab21289994eca7fc9cf1278be7c00683
=> kdc: unused pid element is (pid_t)-1 not zero

lib/roken/parse_time.c, lib/roken/parse_time.h, lib/roken/parse_units.c, lib/roken/parse_units.h, lib/roken/version-script.map
On Debian stretch systems PAM modules linked against Heimdal run into
symbol conflicts with parse_time() in systemd libraries.  We redefine
parse_time() and friends to rk_parse_time(), ... while keeping the old
names for ABI compatibility with existing clients.
The legacy names should eventually be droppped.
=> Try to avoid parse_{time,units,flags} symbol conflicts

lib/krb5/send_to_kdc.c
If the hostname was already set, a typo in a test meant we were not
freeing it.  While we're at it, handle the unlikely possibility that
the existing pointer is passed as the new value.
=> Avoid potential memory leak in krb5_sendto_set_hostname

lib/krb5/krbhst.c
The size of portstr is too small to print an integer and we should print
a short anyway.
This fixes building with GCC 7.1
=> lib: Fix printing a short into portstr

lib/krb5/changepw.c
The default client principal for `krb5_set_password`, if the principal argument were `NULL`, was `krb5_get_default_principal`.  But `krb5_set_password` requires credentials for the password change service be passed in, and those credentials are already associated with a client principal that's much more likely to be the correct choice for a default.  Use that principal instead of `krb5_get_default_principal`.
=> Set default principal for password change to credential client

lib/kadm5/password_quality.c
If the external password quality program returned a failure message, the unparsed form of the principal name was never freed.  Free it.
=> Close memory leak in external_passwd_quality

cf/roken-frag.m4, lib/roken/roken.h.in
Here's a stack overflow article for reference:
http://stackoverflow.com/questions/28022507/solaris-10-alternative-to-dirfd
On Solaris 8 x86 there is no dirfd() or ->dd_fd, so we need to check for ->d_fd also.
=> Solaris 8 x86 uses ->d_fd not ->dd_fd or dirfd()

kadmin/load.c, lib/hdb/db.c, lib/hdb/db3.c, lib/hdb/hdb-ldap.c, lib/hdb/hdb-mdb.c, lib/hdb/hdb-mitdb.c, lib/hdb/hdb-sqlite.c, lib/hdb/hdb.h, lib/kadm5/ipropd_slave.c
This PR makes `kadmin load` and `ipropd-slave`'s `receive_everything()` much faster by not doing any `fsync()`s or `fdatasync()`s or similar (e.g., `O_SYNC`, `sync(2)`, ...).
This should prevent a situation in iprop where a slave receiving a full dump can cause all slaves to persistently need to receive full dumps.  This is not a complete fix for that problem, however.  A more complete fix will follow.
=> Do not fsync() every record when loading HDB from a dump (kadmin and iprop)

kadmin/load.c, kdc/mit_dump.c
When a dump entry has lots of keys or long extensions, the 8192 byte read buffer in load may be insufficient.
=> Handle long lines in dump files

lib/roken/parse_units.c
Skipping any trailing whitespace characters
=> Make parse_units() handle trailing whitespace

lib/roken/getauxval.c, lib/roken/issuid.c
if when we need to determine if getauxval sets errno, we determine it doesn't
after getting a 0 return code, make sure we return a value, since we didn't
previously. fall through to code we'd otherwise have called in this case
above.
=> getauxval: fall through to auxv gfter getauxval errno test

lib/hcrypto/camellia-ntt.h, lib/hcrypto/rand.h
camellia-ntt had none of its symbols renamed into the hc_ namespace,
and rand's missed timer_method (while all other methods were done). rename
these like we do for others
=> hcrypto: implement missed symbol renaming in camellia-ntt and rand

cf/roken-frag.m4
on solaris it's in sys/auxv.h; so a test for it only in auxv.h isn't
enough
=> roken: test for auxv_t in whichever of auxv.h or sys/auxv.h we find

lib/libedit/src/makelist
solaris needs gawk; we should allow the makefile to override awk
with gawk (or whatever else)
=> libedit: makelist should default to awk, but not force it

lib/krb5/crypto-evp.c
Some versions of gcc can't follow the logic in the encryption path
of the _krb5_evp_encrypt_iov_cts code, and believe that it is
possible for the lastpos structure to be used uninitialised.
This isn't actually possible. On entry to the loop, remaining is
guaranteed to be both greater than, and a multiple of blocksize.
In order to exit the loop, remaining must be set to 0. If
cursor.current.length >= remaining, then we set remaining to 0 and
also set lastpos. Otherwise, we calculate the number of whole blocks
in the current iovec, which must be less than remaining, and subtract
that from remaining. Remaining must still be a multiple of and greater
than or equal to blocksize. If remaining == blocksize, we set lastpos,
and set remaining to 0. Otherwise we consume a single block, and go …
=> krb5/crypto: Fix compiler error in new iovec CTS code

lib/kadm5/ipropd_slave.c
log_init in the event a log is found will do recovery. kadm5_log_replay
will call methods which expect an hdb_db to be set but without this
none is
=> ipropd_slave: open hdb around kadm5_log_init in case recovery needed

lib/gssapi/mech/gss_mech_switch.c, lib/krb5/plugin.c
Samba has a cut-down version of Heimdal in-tree, which does not have HAVE_DLOPEN specified. 
This patch allows this to build in Samba, after an update to current Heimdal.
=> heimdal: Use #ifdef HAVE_DLOPEN around functions and variables used by HAVE_DLOPEN

lib/hdb/hdb-mitdb.c
Hi,
Here's a small patch to repair some changes made in 57f1545a. It seems like a line has been mistakenly deleted.
Cheers,
Romain
=> hdb-mitdb: Commit 57f1545a broke support of REQUIRES_PWCHANGE during MIT DB imports

kadmin/kadmin-commands.in, lib/krb5/doxygen.c
=> Correct "princial" typos.

lib/gssapi/krb5/unwrap.c
Zero out the DES_cblock structure instead of the (not yet used at this point
in the function) key schedule.  The contents could potentially be left
on the stack in the case of an error return from _gssapi_verify_pad().
=> GSS unwrap: wipe copy of DES key when done with it

lib/roken/rand.c
In VC15 GetVersionEx has been deprecated.  It is currently only used
to test for versions being >= XP.
Assuming the Win2K and earlier is no longer supported, remove the
test and instead hard wire has_rand_s to be true.
=> Windows: Avoid using deprecated function.

kdc/kerberos5.c, kdc/pkinit.c, lib/gssapi/gss_acquire_cred.3, lib/hcrypto/rand-fortuna.c, lib/krb5/context.c, lib/krb5/data.c, tests/ldap/check-ldap.in
There are some further uses of "inital"/"initalize" in changelog files and old NEWS entries which I left for now as some projects are reluctant to fix typos in such files.  Also some in `lib/sqlite/` but that seems to be an embedded code copy.
=> Fix assorted typos

tests/gss/check-context.in
There is an extra line in tests/gss/check-context.in.  It uses a deleted command.
=> Remove an extra line which uses a deleted command.

lib/krb5/init_creds_pw.c
Without this, in an AS-REQ that has no local key for FAST
we would send the AS-REQ again, which can bump the bad
password count on the KDC twice.
So only try again if FAST was actually tried.
=> lib/krb5: Do not re-send the AS-REQ if fast was disabled

kcm/cache.c
In KCM, when allocating new kcm_ccache struct, there is missing
inicialization of kdc_offset.
It is getting random values in my case and stored tickets are unusable,
last time I got this value to "klist -v":
KDC time offset: 61 years 11 months 2 weeks 3 days 5 hours 28 minutes 32 seconds
This commit seems to correct it.
=> KCM: initialize kdc_offset when allocating kcm_ccache struct

configure.ac, lib/com_err/Makefile.am, lib/com_err/lex.l, lib/libedit/src/makelist, lib/sl/Makefile.am, lib/sl/slc-lex.l
Update with patch from @nicowilliams for makelist change, and add autoconf detection of flex --nounput option so we avoid warnings if it's available.
=> Solaris 10

lib/roken/getauxval.h
The Solaris auxval test fails, because Solaris uses different preprocessor symbols (and numbers) for its UID and GID auxval types.
Note that issuid() could simply be an alias of issetugid() on Solaris, so perhaps this is not necessary.
@nicowilliams please review
=> roken: Solaris auxval test fails (#441)

lib/wind/UnicodeData.py
From Samba
Python2 is EOL soon and Samba builds with python3 by default now so it would be helpful to have this merged upstream.
=> PY3: fix "TabError: inconsistent use of tabs and spaces"

kadmin/ank.c
Adding a principal with a random key or password did not respect non-default password expiration times, because the act of setting the key or password would clobber it with the default. As we update the principal anyway after setting the keys, use this opportunity to restore the requested password expiration time. (There are other ways to solve this, but this is the least intrusive.)
=> kadmin: honour pw-expiration-time when adding principal (#360)

tests/kdc/check-kadmin.in
When we use a custom patch that makes strong passwords required even for
administrators the check-kadmin test will fail because "foo" (the password
used in check-kadmin.in) is not a strong password. So, we make the
password used in check-kadmin.in settable as a parameter. This way, we
only have to change one line of check-kadmin.in rather than a dozen to get
check-kadmin to pass when using the strong-passwords everywhere patch.
Note that this change makes no real change to any of the tests in
check-kadmin.in: no tests are changed, removed, or added.
=> Make the password used in check-kadmin.in be settable as a parameter

lib/hcrypto/evp-pkcs11.c
When building with -m64 on solaris 8 sparc, the build fails with:
evp-pkcs11.c:63:11: error: #if with no expression
On solaris 8, _LP64 is defined as nothing, so we need to check if it's defined, not if it is defined as 1.
gcc 4.6.1
=> solaris 8 sparc defines _LP64 to empty, causing build failure

kuser/kinit.c
kinit does not destroy ccaches created with krb5_cc_new_unique() if ticket acquisition fails. This was leaving dangling keyring entries with the keyring ccache.
=> kinit: don't leave dangling temporary ccaches

lib/kadm5/ad.c, lib/kadm5/chpass_c.c, lib/kadm5/common_glue.c, lib/kadm5/context_s.c, lib/kadm5/create_c.c, lib/kadm5/delete_c.c, lib/kadm5/get_c.c, lib/kadm5/get_princs_c.c, lib/kadm5/get_princs_s.c, lib/kadm5/get_s.c, lib/kadm5/init_c.c, lib/kadm5/ipropd_master.c, lib/kadm5/ipropd_slave.c, lib/kadm5/log.c, lib/kadm5/modify_c.c, lib/kadm5/modify_s.c, lib/kadm5/privs_c.c, lib/kadm5/randkey_c.c, lib/kadm5/rename_c.c, lib/kadm5/rename_s.c, lib/kadm5/send_recv.c, lib/kadm5/set_keys.c, lib/kadm5/set_modifier.c
Perform error checking for each function call and consistently return
errors at the point of failure.
Refactor functions to use a common exit path.  Preserve error messages
stored in the kadm5_client_context.context when appropriate.
Change-Id: I7aa04020e4de3454066f0d88ba805fed999dbd1a
=> lib/kadm5: improve kadm_c_ error handling

doc/setup.texi, kadmin/server.c, kpasswd/kpasswdd.c, lib/krb5/verify_krb5_conf.c, tests/kdc/check-kadmin.in, tests/ldap/check-ldap.in
This patch adds the `enforce_on_admin_set` configuration knob in the `[password_quality]` section. When this is enabled, administrative password changes via the kadmin or kpasswd protocols will be subject to password quality checks. (An administrative password change is one where the authenticating principal is different to the principal whose password is being changed.)
This refactors some of the authorization logic in both kadmind and kpasswdd so please review carefully.
=> kadmin: allow enforcing password quality on admin password change

lib/wind/gen-punycode-examples.py
Update gen-punycode-examples.py for python 3.
gen-punycode-examples.py parses the Sample strings from section 7.1
of rfc3492.txt and generates the punycode_examples.[ch] sources containing
the punycode_examples[].
Python 3 requires that print output be surrounded by parentheses
and the split and join operations have been moved from the "string"
class to built-ins.
This change adds the missing parentheses and switches to the built-in
split and join str operations.
The "string" class is no longer required as an import.
Change-Id: Ic5f341080d2ff2feef692c89e0b28dcbf4e48cb4
=> lib/wind: PY3 gen-punycode-examples.py

lib/ipc/client.c
When connect() fails in connect_unix() the path_ctx.fd is not
set to -1 after close().  When common_release() is executed due
to the error return from connect_unix() it calls close() a second
time.
There is no need to call close() from connect_unix(). Remove the
duplicate request.
This issue was reported by YASUOKA Masahiko.
Change-Id: I825e274cc7f12e50a8779a2b62ddb756817cdb52
=> lib/ipc: client double close of socket file descriptor #431

lib/krb5/send_to_kdc.c
Prior to this change a KDC response of KRB5KDC_ERR_SVC_UNAVAILABLE
would result in the client looping forever.  Setting the action to
KRB5_SENTO_CONTINUE repeats the current loop without altering the
current state.  Hence the infinite loop.
As of this change, the action is set to KRB5_SENDTO_RESET which
forces the current kdc's response to be cleared and then to retry.
If KRB5KDC_ERR_SVC_UNAVAILABLE continues to be returned, the retry
limit will be reached and the loop will end.
This bug was filed by multiple sources including Samba and ScottUrban
on github.
Change-Id: If1611be0ada3422cefae89541ed3b3df1f6efe29
=> lib/krb5: send_to_kdc KRB5KDC_ERR_SVC_UNAVAILABLE infinite loop #346

lib/roken/rand.c
When arc4random() is available, rk_random_init() does not have to
call arc4random_stir().  ac4random_stir() will be called as a result
of the first call to arc4random().
Change-Id: I6f4a3be7c39752746657945ed15896472908f889
=> lib/roken: rk_random_init HAVE_ARC4RANDOM #401

kdc/kerberos5.c, kdc/krb5tgs.c, kuser/kinit.c, lib/krb5/get_cred.c, lib/krb5/init_creds_pw.c, tests/kdc/check-pkinit.in, tests/kdc/check-referral.in
Recently I got involved in @abartlet's efforts to upgrade Heimdal in Samba, and have come up with some patches to help with that.
Note about the last commit, enterprise vs canonicalize; this is now needed in order to be able to test and exercise flows where enterprise name type is used without canonicalize kdc-req-option, and confirm the name is not being canonicalized by the KDC. It used to be done in Samba torture tests by hooking via send_to_kdc and removing the canonicalize flag but this now fails due to PA-REQ-ENC-PA-REP protection.
I noticed a related discussion in issue #452, if we prefer to keep the alignment of the two flags for convenience then perhaps we can move both to kinit code so that other consumer of the API could chose whether or not the canonicalize flag is set (also, …
=> Samba Heimdal upgrade

kadmin/init.c, lib/kadm5/libkadm5srv-exports.def, lib/kadm5/version-script.map
WIP – tests are failing on my end
Since c6bf100b password quality checks have been moved out of kadmindd and into libkadm5. This means that all password changes are subject to quality checks, if enforce_on_admin_set is true (the default). In rare instances it could be possible for realm initialization to fail because the randomly generated passwords do not pass the password quality test. Fix this by creating principals with no password or key, rather than with a random password.
Random *keys* continue to be set immediately after the principal is created, and before DISALLOW_ALL_TIX is unset, so there should be no functionality or security implications from this change. It is safe to call a server-side API such as kadm5_s_create_principal_with_key() as local_flag is asserted to be true.
=> kadmin: do not assign passwords at realm initialization

lib/hcrypto/ui.c
UI_UTIL_read_pw_string(), an interface borrowed from OpenSSL, should report password verification failure to stderr.
=> hcrypto: print failure on password mismatch (#469)

.travis.yml, tests/ldap/slapd-init.in, tests/ldap/slapd.conf
From the commit:
```
We start slapd in the foreground (-d0) but backgrounded in the shell,
then we wait 4 seconds.  This causes a race condition however.  This
commit makes the slapd-init script more robust and limits the wait to
however many seconds (up to 30) that slapd needs to start service.
```
The fix is to loop up to N times checking that `slapd` is responsive, sleeping a second in between.
=> Fix check-ldap race condition (fix #482)

admin/add.c, appl/otp/otp.c, kadmin/ank.c, kadmin/cpw.c, kadmin/stash.c, kdc/kstash.c, kpasswd/kpasswd.c, lib/hcrypto/ui.c, lib/hcrypto/ui.h
Add flag to `UI_UTIL_read_pw_string()` to suppress verification failure message
=> libhcrypto: UI_UTIL_FLAG_VERIFY_SILENT (#469)

kadmin/Makefile.am, kadmin/NTMakefile, kadmin/kadmin-commands.in, kadmin/kadmin.1, kadmin/prune.c, kadmin/server.c, lib/hdb/keys.c, lib/hdb/libhdb-exports.def, lib/hdb/version-script.map, lib/kadm5/Makefile.am, lib/kadm5/NTMakefile, lib/kadm5/common_glue.c, lib/kadm5/context_s.c, lib/kadm5/init_c.c, lib/kadm5/libkadm5srv-exports.def, lib/kadm5/private.h, lib/kadm5/prune_c.c, lib/kadm5/prune_s.c, lib/kadm5/version-script-client.map, lib/kadm5/version-script.map, tests/kdc/check-kadmin.in
Hello,
please consider and at least comment this PR.
In current implementation (without PR)
* the old keys either stays in the database forever or are prunned 
automagically based on max_lifetime (based on prune-key-history), but 
only on `cpw`, and yet it left the old key in history forever.
* Rotating krbtgt/ (or other principals) wihtout `--keepold` would disrupt 
realm operations, eg. long computing grid jobs.
The added functionality:
* can be used to prune historic keys from principal
history by selective kvno. The main usecase is rollover krbtgt/ principals 
(self and crossrealms).
* it should be backward compatible afaik despite new opcode 
`kadm_ops` struct. During operation a 'modify' type is logged into iprop 
journal but data already contains and ipro processes full key history …
=> kadmin selective prune of historic key for principal

kadmin/server.c
Coverity determined that a NULL pointer segmentation fault could occur
if krb5_storage_emem() fails.  Use krb5_enomem() to set an error message
on the context and do not perform further krb5_storage operations.
=> kadmin: kadmin_dispatch out of memory handling

kdc/krb5tgs.c, lib/hdb/common.c, lib/hdb/hdb.asn1
e11abf41 added support in libhdb for always dereferencing principal aliases during an AS-REQ (where dereferencing refers to enabling alias lookups, and rewriting the returned entry with the alias name unless canonicalization was enabled).
Due to the KDC setting `HDB_F_FOR_AS_REQ` for all lookups from the AS, this allowed aliases on the TGS itself to be dereferenced during an AS-REQ; however, on presenting the TGT, the TGS would fail to resolve. Creating an explicit TGS principal for the aliased realm would work (at least prior to c555ed6a), but  this could be confusing to deploy.
This commit changes enables alias dereferencing when `HDB_F_GET_ANY` is set, which essentially means dereference whenever the request is coming from the KDC (as opposed to, say, kadmin).
We also backout c555ed6a, …
=> hdb: dereference principal aliases in all KDC lookups (#452)

kdc/kerberos5.c, lib/hdb/common.c
Mirroring the logic recently introduced in the TGS, this patch modifies the KDC to perform client and server canonicalization itself rather than relying on the backend to do so. Per RFC 6806, the behavior is slightly different for the AS in that the setting of the canonicalize flag in the AS-REQ _does_ impact the returned names in the ticket. In order to support realm canonicalization or other custom behavior, we allow the backend to force the KDC to canonicalize by setting the `force-canonicalize` flag in the returned client or server entries.
Rationale: name canonicalization behavior should be as consistent as possible between the AS and TGS; naming logic does not belong in the HDB. (I'd also like to move `KRB5_NT_ENTERPRISE_PRINCIPAL` handling from HDB to the KDC, but I've left that …
=> kdc: perform AS-REQ canonicalization in kdc

lib/asn1/asn1_gen.c, lib/asn1/gen.c, lib/asn1/gen_decode.c, lib/asn1/gen_glue.c, lib/asn1/test.asn1, lib/roken/parse_units.h
Wait for builds and tests before reviewing.  Also: need to add a test.
The ASN.1 compiler now uses `uint64_t` for `BIT STRING` bitsets with between 33 and 64 members.
For `BIT STRING` bitsets with more than 64 members, no `<type>2int()` nor `int2<type>()` functions are generated, and the application can then only encode/decode.
=> ASN.1: Support wider bit sets (fix #514)

lib/roken/tsearch.c
The rk_UNCONST macro exists because neither __DECONST nor uintptr_t
are available on all platforms (for example, AIX).
=> roken: tsearch use rk_UNCONST instead of __DECONST  #307

lib/hx509/data/gen-req.sh, lib/hx509/data/mkcert.sh
Modern OpenSSL no longer has the 2038 year restriction.  Update the
certs to last 500 years rather than 10 years.
Modern crypto requirements suggest a stronger key strength than 1024.
Update to use a minimum of 4096.
Fix executable bit on gen-req.sh
=> For https://github.com/heimdal/heimdal/issues/392

lib/roken/NTMakefile, lib/roken/getaddrinfo-test.c
Before we call gettaddrinfo we have to call rx_SOCK_INIT
In order to exercise the test we have to supply parameters to the command line
=> Windows: Make getaddrinfo-test work

lib/asn1/Makefile.am
the rule to generate test_template_asn1-template.c from
test_template_asn1-template.x was missing. add it.
=> tests: generate test_template_asn1-template.c for testing

kdc/kerberos5.c, kuser/kinit.c, kuser/kuser_locl.h, lib/krb5/krb5.h, lib/krb5/libkrb5-exports.def.in, lib/krb5/principal.c, lib/krb5/ticket.c, lib/krb5/version-script.map
_krb5_principal_is_anonymous() is used outside lib/krb5 and
therefore it needs to be properly exported and its flag macros
need to be in a public header: krb5.h not krb5_locl.h.
Including krb5_locl.h from within kuser_locl.h for instance
results in build failures on Solaris.
This change renames the function and makes it part of the public
api.
Change-Id: I130d1698b10bdbd150b95e8c7d32dfc362889ce6
=> make krb5_principal_is_anonymous public

lib/krb5/send_to_kdc.c
The combination of 8740528b2477f872147998ca19a66d2fae12631b
("Windows-compatible sentinel socket type and value") and
d497d7e4a796c6bda153e7f10fe9478724b855ab ("krb5_sendto_kdc:
failover for multiple AAAA/A RRs on one domain") broke
all the send to kdc loop on Windows.  rk_socket_t is
a HANDLE and rk_INVALID_SOCKET is the max value.  Therefore,
no valid socket will be larger and all communications
will fail.
Change-Id: I3464f78d67b19f14050ad7a01738fb32bac99385
=> Fix sendto_kdc on Windows

lib/hcrypto/evp-pkcs11.c, lib/krb5/send_to_kdc.c
The cherry pick of 934d5e09bf3ba0774d303da53446e5ff94daae01 dropped
the initialization of p11_module_load() *ppFunctionList to NULL.
Change-Id: I0b07315c040340c7ca95ff87fd985c6c7e865aeb
=> Fix to 7.6.0 release for Solaris and Windows

lib/hcrypto/evp-pkcs11.c
Before committing to a PKCS#11 mechanism, check that it can provide the
required encryption or digest services by validating the flags returned by
C_GetMechanismInfo().
(cherry picked from commit 5c70e5015edbe056eb192c166c3056c29d70482b)
=> hcrypto-pkcs11: check mechanism flags

lib/krb5/get_cred.c, lib/krb5/get_in_tkt.c, lib/krb5/init_creds_pw.c, lib/krb5/krb5_locl.h, lib/krb5/ticket.c
Verify the KDC recognized the request-anonymous flag by validating the returned client principal name.
=> krb5: check KDC supports anonymous if requested

kdc/krb5tgs.c, lib/krb5/libkrb5-exports.def.in, lib/krb5/version-script.map, tests/kdc/check-kdc.in
even if tgt used an enctype with a different checksum.
Per [MS-SFU] 2.2.1 PA-FOR-USER the checksum is always
HMAC_MD5, and that's what Windows and MIT clients send.
In heimdal both the client and kdc use instead the
checksum of the tgt, and therefore work with each other
but windows and MIT clients fail against heimdal KDC.
Both Windows and MIT KDC would allow any keyed checksum
to be used so Heimdal client work fine against it.
Change Heimdal KDC to allow HMAC_MD5 even for non RC4
based tgt in order to support per-spec clients.
=> kdc: allow checksum of PA-FOR-USER to be HMAC_MD5

kdc/krb5tgs.c, lib/krb5/libkrb5-exports.def.in, lib/krb5/version-script.map, tests/kdc/check-kdc.in
even if tgt used an enctype with a different checksum.
Per [MS-SFU] 2.2.1 PA-FOR-USER the checksum is always
HMAC_MD5, and that's what Windows and MIT clients send.
In heimdal both the client and kdc use instead the
checksum of the tgt, and therefore work with each other
but windows and MIT clients fail against heimdal KDC.
Both Windows and MIT KDC would allow any keyed checksum
to be used so Heimdal client work fine against it.
Change Heimdal KDC to allow HMAC_MD5 even for non RC4
based tgt in order to support per-spec clients.
Back ported from master, commit:
b7fe0fb85a780fed3c54ed2539fc974db1884dc2
=> [7.1 back port] kdc: allow checksum of PA-FOR-USER to be HMAC_MD5

kuser/kinit.c, tests/kdc/check-kdc.in
Anonymous PKINIT tickets discard the realm information used to locate the issuing AS. Store the issuing realm in the credentials cache in order to locate a KDC which can renew them.
=> kuser: allow kinit to renew anonymous PKINIT tickets

lib/krb5/Makefile.am, lib/krb5/NTMakefile, lib/krb5/ccache_plugin.h, lib/krb5/common_plugin.h, lib/krb5/krb5.h, lib/krb5/plugin.c
This series fixes build issues on Windows related to the new common plugin api and makes the common plugin interface public for consumption by third party plugins.
=> Make common plugin api public

include/config.h.w32, lib/roken/NTMakefile
The fix involves:
- Removing HAVE_STRFTIME from config.h.w32
- Adding strftime.c to the makefile
- Defining timezone and tzname to their windows equivalent
for the compile of this module
=> Windows:   Windows CRT doesn't support %k as format for strftime

kadmin/kadmin.1
At one point in time, the configuration option was named
"password-quality" but this was later changed to
"verify-password-quality".  Update the kadmin(1) man page to reflect
this change.
=> Fixes heimdal#535 - verify-password-quality

kdc/hprop.8
There are two options to hprop.  It's important to note that the default
behavior is to transmit the database with encrypted keys.
=> Fixes #550 - Note that encrypt is the default option

kadmin/kadmind.8
Update the kadmind(8) man page to note that the "all" option for ACLs
does not include the "get-keys" option.
=> Fixes #532 - Note that all does not include get-keys

kadmin/kadmin.1
backends
When running with verify-password-quality and a back-end that stores
history (such as heimdal-history) this command can cause an update to
the database meaning the password can no longer be used with this
principal in the future
=> Fixes #536 - Note that this can cause unexpected behavior with certain

lib/krb5/get_cred.c
CC @lhoward 
Constrained delegation fails on master, after commit: 014e318d
I get BADOPTION at: https://github.com/heimdal/heimdal/blob/014e318d6bdefd8ecfcb99ca9928921f6a49d721/lib/krb5/ticket.c#L727
Any idea why is S4U2Proxy automatically set to anonymous? I didn't see a mention of it elsewhere.
If I remove the anonymous flag as in this patch then it works okay.
To reproduce:
$ echo pwd | kinit -f impersonator@REALM
$ kgetcred --out-cache=evidence --impersonate=user@REALM impersonator@REALM
$ kgetcred --debug --delegation-credential-cache=evidence --out-cache=out -H HTTP/apache.realm@REALM
$ KRB5CCNAME=out curl --negotiate -u: http://apache.realm/whoami.aspx
=> Do not set anonymous flag in S4U2Proxy request

kdc/kerberos5.c, kdc/krb5tgs.c
Drafts 0 through 10 of the Kerberos anonymity draft specified the
TicketFlags.anonymous flag as bit 14.  This was changed to bit 16
after it was discovered that Microsoft used bit 14 for S4U2Proxy.
d5bb7a7c566841d52662b230248f06522bfa64ad ("(krb5_get_creds): if
KRB5_GC_CONSTRAINED_DELEGATION is set, set both") set both the
anonymous and constrained_delegation TicketFlags when issuing a
S4U2Proxy request.  The setting of the anonymous TicketFlag was
removed by ea7615ade3af28843f358e715703226b760db73b("Do not set
anonymous flag in S4U2Proxy request").
014e318d6bdefd8ecfcb99ca9928921f6a49d721 ("krb5: check KDC
supports anonymous if requested") introduced a client side check
to ensure that an anonymous request is responded to with an
anonymized ticket.  The combination of setting the …
=> kdc: history of request_anonymous vs cname-in-addl-tkt confusion

kdc/kerberos5.c
Instead of returning an error if the client asks for
a forwardable ticket where it isn't allowed, we simply
return one that isn't forwardable.
This is roughly analogous to how we take the min(requested lifetime, configured lifetime).
=> kdc: no error if req is fwdable on non-fwdable princ

kdc/default_config.c, kdc/kdc.8, kdc/kdc.h, kdc/kerberos5.c, kdc/pkinit.c, kuser/kinit.1, kuser/kinit.c, lib/krb5/krb5.conf.5, lib/krb5/krb5.h, lib/krb5/principal.c, lib/krb5/ticket.c
* Anonymous pkinit responses from the KDC where the name
type is not well-known (as issued by 7.5 KDCs and earlier)
are accepted by the client.  There is no need for the client
to strictly enforce the name type.
* With historical_anon_pkinit = true, the kinit(1) client's
"--anonymous" option only performs anon pkinit, and does
not require an '@' prefix for the realm argument.
* With historical_anon_realm = true, the KDC issues anon
pkinit tickets with the legacy pre-7.0 "real" realm.
=> Optional backwards-compatible anon-pkinit behaviour

lib/kadm5/ipropd_master.c
When the master sees a burst of updates (perhaps sustained), the
slaves "I_HAVE" messages can fall behind the version we've already
sent, and the unpatched code would retransmit already sent diffs!
This can result in substantial amplification (in a local test, 3000
ops turned into 427,000 ops).  Though the number of *messages* sent
was actually somewhat smaller, the ever growing message size
ultimately leads to failure.
=> Don't stutter in send_diffs

lib/kadm5/init_c.c, lib/krb5/expand_path.c, lib/krb5/get_default_principal.c, lib/krb5/krb5.conf.5, lib/roken/getuserinfo.c, lib/roken/roken.h.in, lib/roken/test-getuserinfo.c, lib/roken/version-script.map
We add a new `%{loginname}` to mean "that which is returned by `getlogin_r()`", and make `%{username}` mean only whatever `$USER`, or `$LOGNAME`, or `getpwuid_r()` say.  And we make sure that the default principal name, and the principal name `kadmin` defaults to, are based on the former when running as root and the latter otherwise.
=> Support builds as non-logged-in root

configure.ac, include/config.h.w32, lib/kadm5/get_s.c, lib/kadm5/ipropd_master.c, lib/kadm5/ipropd_slave.c, lib/kadm5/kadm5_locl.h, lib/kadm5/libkadm5srv-exports.def, lib/kadm5/log.c, lib/kadm5/version-script.map, tests/kdc/check-iprop.in
This work makes `ipropd-master` use async I/O for most of what it does -- everything except authentication of the peer.  Along with using async I/O, `ipropd-master` now chunks the sending of full props and diffs so no peer can keep others from getting serviced.
All but the last commit are also ultimately intended for 7.x, where until now iprop was much too fragile, and remains so to some degree without these changes.
The last commit is only needed when a slave is down for a long time, but the log is large enough for it to catch up from just the log.  We might then try to send it many transactions all at once, (non-blocking, ...) but still large memory footprint on master, and risk of clock-skew on slave by the time it receives the entire batch of changes. It is however much more complex …
=> Async iprop, take 2

doc/standardisation/rfc6717.txt, kdc/default_config.c, kdc/kx509.c, kdc/process.c, kuser/Makefile.am, kuser/NTMakefile, kuser/heimtools-commands.in, kuser/klist.1, kuser/klist.c, lib/asn1/kx509.asn1, lib/hx509/ks_file.c, lib/krb5/Makefile.am, lib/krb5/NTMakefile, lib/krb5/cache.c, lib/krb5/krb5.conf.5, lib/krb5/krb5.h, lib/krb5/kx509.c, lib/krb5/kx509_err.et, lib/krb5/libkrb5-exports.def.in, lib/krb5/version-script.map, tests/gss/krb5.conf.in, tests/kdc/Makefile.am, tests/kdc/check-pkinit.in, tests/kdc/krb5-pkinit.conf.in
This commit adds support for kx509 in libkrb5, and revamps the KDC's kx509 service (fixing bugs, adding features).
Of note is that kx509 is attempted optimistically by the client, with the certificate and private key stored in the ccache, and optionally in an external PEM or DER file.  This allows users to have PKIX credentials wherever they have Kerberos credentials.  If the service is configured to not require INITIAL tickets, then this functionality amounts to a PKIX credential delegation feature of sorts: wherever a user delegates Kerberos credentials, they can also automatically have PKIX credentials.
A number of related commits are in this PR.  Perhaps those should be separated and pushed first.
There's a lot of work to be done yet, but most if not all of it can be done in later …
=> Add kx509 client and revamp kx509 service

kdc/connect.c, kdc/digest-service.c, kdc/digest.c, kdc/fast.c, kdc/kerberos5.c, kdc/krb5tgs.c, kdc/kx509.c, kdc/misc.c, kdc/set_dbinfo.c, lib/krb5/krb5_openlog.3, lib/krb5/log.c
We define the meaning of the various log levels in the man page
for krb5_openlog(3).  If logging configured and levels are not
specified, we change the default levels to 0-3 which should exclude
debugging messages which are generally only desired in exceptional
circumstances.
We also go through the KDC and adjust the levels to be appropriate.
=> Define log levels in docs and change default to 0-3.

cf/make-proto.pl, kuser/kinit.1, kuser/kinit.c, lib/gssapi/krb5/init_sec_context.c, lib/krb5/Makefile.am, lib/krb5/NTMakefile, lib/krb5/addr_families.c, lib/krb5/get_for_creds.c, lib/krb5/krb5.conf.5, lib/krb5/libkrb5-exports.def.in, lib/krb5/mk_cred.c, lib/krb5/version-script.map
This allows you to configure (in `/etc/krb5.conf`) that certain realms will "delegate-destination-tgt".  That is, rather than delegating a full TGT of the form krbtgt/START@START, you delegate a TGT of the form krbtgt/DEST@DEST. The interesting thing here is that the destination realm becomes a bit like the hotel california because you can't come back to the original realm as that will violate its transited policy.
This functionality works well for DMZ realms and the like where you want to allow access---and you want to be able to delegate creds which people can use to continue to SSH around in the DMZ, but you do not want them to be able to SSH back into the main environment.
=> Delegate destination TGT support

kdc/misc.c
We copy the princ in the hdb_entry so that if it is later used, it
will reflect what we want.
=> derived keys: ensure that princ is correct

lib/krb5/expand_path.c, lib/krb5/krb5.h, lib/krb5/krb5_openlog.3, lib/krb5/log.c
So, here we define %{strftime:<string>} in our path expansion routines and then subject logging file definitions to token expansion. Now, we can do something like this:
[kdc]
kdc = FILE:/var/log/auth/%{strftime:%Y%m%d%H}
for nice automatically rolling over logs.
=> Strftime expand tokens

lib/krb5/crypto.c, lib/krb5/libkrb5-exports.def.in, lib/krb5/version-script.map
This function is quite useful for a project on which I am working. We _may_ want to rename it or update the usage in some fashion before we export it?
=> Export krb5_crypto_prfplus() from libkrb5

cf/roken-frag.m4, lib/roken/getauxval.h
This fixes the auxval logic on NetBSD.
=> include <sys/exec_elf.h> if it's available.

.gitignore, NTMakefile, cf/w32-check-exported-symbols.pl, lib/hx509/hxtool.c, lib/krb5/libkrb5-exports.def.in, lib/krb5/test_cc.c, lib/roken/test-detach.c
Looks like this partially fixes the Appveyor build.
We now need to fix the building of the documentation. It's missing a Perl module at the moment, which is likely just a tweak to Appveyor @jaltman? Or alternately, we could change appveyor to pass `--disable-heimdal-documentation` to `./configure`. This should fix the build as the documentation is the last thing to build---and we are getting there.
=> Declare variables at the beginning of a block.

lib/gssapi/krb5/init_sec_context.c, lib/krb5/context.c, lib/krb5/krb5.conf.5, lib/krb5/krb5_locl.h
If this flag is set to true, then GSSAPI credential delegation will
be disabled when the "ok-as-delegate" flag is not set in the service
ticket.
=> Add enforce_ok_as_delegate setting

lib/asn1/libasn1-exports.def
In 0cc708ba36, we removed the definition of id-ms-client-authentication
without a corresponding removal from lib/asn1/libasn1-exports.def.
Maybe we should generate lib*-exports.def?
=> Fix windows build

kdc/kx509.c
bcb5ed28fbe25d3b207d17ddd2f420f938a4ef03 ("kdc/kx509.c: clean up
krb5_get_error_message strings used for mk_error_resp") introduced a
build failure.  'context' is not a local variable but a field in the
kx509_req_context.
Change-Id: I38a8a9b1a19c3370dfc039d6e09445425936c32b
=> kdc: kx509.c fix build failures

lib/hcrypto/Makefile.am, lib/hx509/Makefile.am
automake 1.16 and later don't work on the 7.1-branch without these fixes
=> pull up automake fixes from master so proper dependencies exist even with newer automake

cf/roken-frag.m4, lib/gssapi/spnego/accept_sec_context.c, lib/gssapi/spnego/compat.c, lib/gssapi/spnego/init_sec_context.c, lib/roken/NTMakefile, lib/roken/mergesort.c, lib/roken/mergesort_r.c, lib/roken/roken.h.in, lib/roken/version-script.map
Sort the list of mechanisms proposed by the initiator so that mechanisms are preferred by their advertised support for GSS flags. For example, if GSS_C_MUTUAL_FLAG is requested, a mechanism that offers GSS_C_MA_AUTH_TARG will be preferred over one that doesn't. The flag/mechanism attribute combinations are also assigned a weight (mutual trumps anonymous, for example).
=> gss: order SPNEGO proposed mechs by req_flags

lib/gssapi/krb5/accept_sec_context.c, lib/gssapi/mech/gss_accept_sec_context.c, lib/gssapi/ntlm/accept_sec_context.c, lib/gssapi/ntlm/init_sec_context.c
If an initial security context token doesn't have a standard header per
RFC2743 then try all mechanisms until one succeeds or all fail.
We still try to guess NTLMSSP, raw Kerberos, and SPNEGO, from tasting
the initial security context token.
=> Better support for "non-standard" GSS mechs

lib/gssapi/sanon/accept_sec_context.c, lib/gssapi/sanon/crypto.c, lib/gssapi/sanon/init_sec_context.c, lib/gssapi/sanon/inquire_context.c, lib/gssapi/sanon/negoex.c, lib/gssapi/sanon/sanon_locl.h
draft-howard-gss-sanon-13 will move extended (RFC4757) flags from the NegoEx metadata to an optional component of the initial context token
=> gss: update SAnon for draft-howard-gss-sanon-13

lib/hcrypto/rsa-ltm.c, lib/hcrypto/test_rsa.c
This commit fixes all the warnings in `lib/hcrypto/rsa-ltm.c`, which were mostly use of deprecated libtommath functions and ignoring their return values.  One warning is introduced that is safe to ignore.
Also, this commit re-writes how RSA keys are generated.  We pick a random number, make it odd, then set the high nibbles of `p` and `q` to be from a nibble pair chosen at random from a list of 32 such pairs such that the product `pq`'s high nibble will be at least 128.  Then we test for primality, and loop if not.
=> hcrypto: Fix warnings in LTM

lib/krb5/mcache.c
We've been hitting this deadlock with a customer using heimdal 7.7, found this was fixed back in 2018 but not integrated into 7.7.  Submitting PR for issue.
=> Deadlock in lib/krb5/mcache.c #432

lib/gssapi/krb5/gsskrb5_locl.h, lib/gssapi/mech/gss_krb5.c
Now that MEMORY:anonymous is... not re-resolvable, gss_krb5_copy_ccache()
is busted.  This commit makes it use gss_store_cred_into2().
This brings up a point: making MEMORY:anonymous what it is breaks
gss_inquire_cred_by_oid() with GSS_KRB5_COPY_CCACHE_X, so we may have to
back that out.
=> Fix gss_krb5_copy_ccache() (broken by MEM:anon)

appveyor.yml, lib/krb5/config_file.c, lib/krb5/get_cred.c
appveyor: Install zstd before other pkgs
krb5: krb5_config_parse_debug initialize output parameters
lib/krb5: not_found() do not substitute the error text
=> Pullups from master for 7-1-branch

kdc/kerberos5.c, lib/base/expand_path.c, lib/base/log.c, lib/gssapi/mech/context.c
This avoids these compiler warnings on Ubuntu 18.04
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
expand_path.c: In function ‘expand_token’:
expand_path.c:493:17: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
asprintf(&arg, "%.*s", (int)(token_end - colon - 1), colon + 1);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
log.c: In function ‘fmtkv’:
log.c:646:5: warning: ignoring return value of ‘vasprintf’, declared with attribute warn_unused_result [-Wunused-result]
vasprintf(&buf1, fmt, ap);
^~~~~~~~~~~~~~~~~~~~~~~~~
mech/context.c: In function ‘gss_mg_set_error_string’:
mech/context.c:212:5: warning: ignoring return value of ‘vasprintf’, declared with attribute warn_unused_result [-Wunused-result]
(void) …
=> Check some error returns from *asprintf()

lib/base/common_plugin.h, lib/heimdal/NTMakefile, lib/krb5/acache.c, lib/krb5/cache.c, lib/krb5/dcache.c, lib/krb5/fcache.c, lib/krb5/kcm.c, lib/krb5/krb5.h, lib/krb5/krcache.c, lib/krb5/mcache.c, lib/krb5/pcache.c, lib/krb5/plugin.c, lib/krb5/scache.c, lib/roken/NTMakefile, lib/roken/roken.h.in, lib/roken/win32_version.c
- lib/krb5: krb5_get_instance does not work on Windows 7
- base: common_plugin.h define KRB5_CALLCONV / KRB5_LIB_CALL
- krb5: krb5_cc_ops backward compatibility and extensibility
=> Fix krb5_ccache plugins on master 

.travis.yml, lib/gssapi/mech/gss_krb5.c
This should make it harder to introduce problem code into Heimdal and make it easier to import a new Heimdal version into Samba (where very strict warning options are in use).
Compiler warning options are very compiler version dependent so this list will need to be refined as the compiler used in Travis CI is upgraded.
=> Catch many compile warnings as errors in Travis CI with -Werror via --enable-developer

lib/base/heimbase.h, lib/krb5/config_file.c, lib/krb5/context.c, lib/krb5/krb5.h, lib/krb5/verify_krb5_conf.c
ea90ca86664c73fb8d415f3cc7baacdf8a6dd685 removed the definition of struct krb5_config_binding which is required by callers of krb5_config_get_list() and krb5_config_vget_list().   
This PR permits out of tree callers to continue using these functions.  Since the structure was public it cannot be changed or removed unless krb5_config_get_list() and krb5_config_vget_list() are unsupported.
=> Callers of krb5_config_[v]get_list() require struct krb5_config_binding

lib/base/context.c, lib/gssapi/krb5/delete_sec_context.c, lib/hx509/cert.c, lib/krb5/context.c
The implementation of hx509_context_free() fails to free the parsed configuration file data.
On Windows, no differentiation was made between KRB5_CONFIG and new configurations such as HX509_CONFIG when obtaining configuration file lists from the registry.
=> hx509 context memory leaks

lib/gssapi/krb5/acquire_cred.c
acquire_cred_with_password() must call
krb5_get_init_creds_opt_set_default_flags() to initialize the
krb5_get_init_creds option flags to the values obtained from
the krb5_context.
Change-Id: Icd8c500dd0787a781c2382284f19cef277b1d30b
=> gss/krb5: acquire_cred_with_password set opt default flags

lib/gssapi/krb5/acquire_cred.c, lib/gssapi/krb5/arcfour.c, lib/gssapi/krb5/cfx.c, lib/gssapi/test_context.c, lib/kafs/afssysdefs.h
- 61c845761 kafs: disable use of AFS syscall on macOS
- 87ab10e3d gss/krb5: acquire_cred_with_password set opt default flags
- 3baf636ac gssapi/krb5: make PADDING buffer optional in GSS IOV API
- b75cc5449 gssapi/krb5: fix rc4-hmac gss_unwrap_iov() without DCE_STYLE
- e1b6a7480 gssapi/krb5: use GSS_IOV_BUFFER_FLAG_ALLOCATE constants
- 0108aa85a gssapi/krb5: ensure singleton buffer in _gk_find_buffer()
- c8abd9aa5 gssapi/krb5: treat empty padding buffers as absent
=> heimdal 7 1 branch pullups

lib/asn1/asn1-template.h, lib/asn1/der_get.c, lib/asn1/gen.c, lib/asn1/gen_decode.c, lib/asn1/gen_glue.c
These two commits fix transient failures of the in-tree tests on Windows i386.
For discussion only at this point.   The impact of the ASN1CALL change on 32-bit Windows consumers must be evaluated in more detail.
=> Fix Windows i386 test failures

lib/krb5/cache.c
`krb5_cc_resolve_sub()` redundantly checks the collection name for a cctype, and also assumes that `cctype` can be NULL (which is not the case as `get_default_cc_type()` always returns non-NULL).
=> krb5: simplify krb5_cc_resolve_sub() logic

lib/hdb/Makefile.am, lib/hdb/hdb-ldap.c, lib/hdb/hdb.c, lib/hdb/hdb.h, lib/hdb/test_namespace.c
The current state of the world is such that the default HDB is named `"heimdal"` in the `LOCALSTATEDIR`, so typically it's `/var/heimdal/heimdal`.  The actual backend for this is to be determined at run-time because a backend type prefix is not part of the default HDB name.
Well, the default backend type selection at run-time depends build configuration.  So if you have BDB installed but not LMDB, you'll get BDB as the default backend, but if you later install LMDB and rebuild Heimdal then default backend type selection will change, and if you install the resulting artifacts and restart a KDC that was running with the default HDB... the KDC will fail to start!
The fix is to be a bit smarter about default backend selection.
This PR includes two commits:
- The first commit implements HDB …
=> hdb: Remove default HDB backend footgun

lib/hdb/Makefile.am, lib/hdb/hdb-sqlite.c, lib/hdb/test_concurrency.c
Test that we can dump an HDB w/o blocking write transactions.
This currently works for different processes (both backends), but not
for threads (for either backend), and it's not yet clear why.
=> hdb: Test LMDB and SQLite3 HDB concurrency

lib/gssapi/gss-token.1, lib/gssapi/gss-token.c, lib/gssapi/gssapi/gssapi.h
We present a series of improvements and fixes to gss-token(1). We clean up and restructure the code a bit. We re-implement a couple of flags that were forgot when it was imported and changed to use getargs(). We make the code implement a proper GSS loop rather than assuming that there is only a single input and output token. We provide a mechanism to split up tokens to test new functionality that is being developed. And finally, we implement a way to ask GSS to use a particular mech on the initiator side.
=> gss-token(1) improvements and fixes.

cf/check-var.m4
autoconf-2.70 and newer are more strict with quoting etc. and thus generate
a broken configure file:
```
configure: 20855: Syntax error: ")" unexpected (expecting "fi")
```
Gentoo-bug: https://bugs.gentoo.org/776241
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>
=> autoconf-2.70 fix

lib/krb5/kerberos.8
While Ken Hornstein's FAQ was useful in its day, much of its content
is no longer relevant (e.g., Kerberos 4) or even actively harmful
(e.g., the latest version of MIT krb5 is not 1.2.1).  It was also
somewhat MIT-krb5-focused, especially relating to configuration file
snippets, which is not necessarily a great fit for the Heimdal
documentation.
Replace it with a tutorial hosted on kerberos.org and the classic
"dialogue" from Bill Bryant.
=> Replace dead link in kerberos.8

kdc/krb5tgs.c
This is a patch to help Samba merge in a current upstrem Heimdal and is selected out of a larger patch by @metze-samba 
It looks like this codepath is tested by server_uu / check-uu but I've not manually checked it.
When b->kdc_options.enc_tkt_in_skey is set, the variable 'spn'
provided to verify_flags() for the purpose of logging is not
yet set, it is still NULL from the initialiser.
On Samba we see, when compiling with -O3 and strict warning rules with
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04):
$ make -k
PYTHONHASHSEED=1 WAF_MAKE=1  ./buildtools/bin/waf build
Waf: Entering directory `/home/abartlet/heimdal-import/samba/bin/default'
Selected embedded Heimdal build
[2822/4527] Compiling source4/heimdal/kdc/krb5tgs.c
In function ‘verify_flags’,
inlined from ‘verify_flags’ at …
=> Provide the correct principal name to verify_flags() for user2user tickets

lib/gssapi/mech/gss_mech_switch.c
Samba compiles Heimdal internally without HAVE_DLOPEN to keep
to internally supplied mechanisms and plugins.
Samba compiles with strict warning flags and on Ubuntu 20.04
with gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) we see:
../../source4/heimdal/lib/gssapi/mech/gss_mech_switch.c: In function ‘_gss_load_mech’:
../../source4/heimdal/lib/gssapi/mech/gss_mech_switch.c:462:1: error: label ‘out’ defined but not used [-Werror=unused-label]
462 | out:
| ^~~
cc1: all warnings being treated as errors
=> Move out: label to inside #endif of HAVE_DLOPEN

kdc/krb5tgs.c
73debbc1668adb4080165fcc1a7028ecae36e9b7 accidentially reverted
the critical part of 040a093654bfbb602ef0ab9807f51a5c83cf9596,
presumably during conflict resolution.
Found by a strict Samba compile during import of current Heimdal.
See #780
=> Fix user2user principal (again)

kdc/kerberos5.c
On Ubuntu 20.04 with gcc version 9.3.0 in a Samba compile
using -Wdiscarded-qualifiers and -Werror we get:
../../source4/heimdal/kdc/kerberos5.c:2516:21: warning: passing argument 2 of ‘_kdc_set_e_text’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
2516 |  _kdc_set_e_text(r, "Client have no reply key");
|                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
../../source4/heimdal/kdc/kerberos5.c:428:42: note: expected ‘char *’ but argument is of type ‘const char *’
428 | _kdc_set_e_text(astgs_request_t r, char *fmt, ...)
|                                    ~~~~~~^~~
=> Add const to _kdc_set_e_text()

lib/hdb/hdb.c
On Ubuntu 20.04 with gcc version 9.3.0 during a strict
Samba build with -Werror=maybe-uninitialized we get:
../../source4/heimdal/lib/hdb/hdb.c: In function ‘hdb_create’:
../../source4/heimdal/lib/hdb/hdb.c:831:13: error: ‘ret’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
831 |     if (*db && ret == 0)
|         ~~~~^~~~~~~~~~~
cc1: all warnings being treated as errors
=> Initialise err in hdb_create()

lib/roken/resolve.c
In a strict Samba build with -Werror=strict-overflow on Ubuntu 18.04
with gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
we see
../../source4/heimdal/lib/roken/resolve.c: In function ‘rk_dns_srv_order’:
../../source4/heimdal/lib/roken/resolve.c:639:7: error: assuming signed overflow does not occur when simplifying conditional to constant [-Werror=strict-overflow]
if(num_srv == 0)
^
cc1: all warnings being treated as errors
This avoids the issue by additionally setting a distinct flag.
=> Avoid -Werror=strict-overflow on in rk_dns_srv_order()

kdc/fast.c, lib/hdb/hdb.h
Samba uses the HDB flags extensively to separate out the different principal types, so it is helpful to indicate the FAST key lookup with a flag, and to supply the correct server name to lookup when looking for the krbtgt.
=> Supply useful HDB flags for FAST

kdc/kerberos5.c
Windows does not check the password on an account that has been locked.
Heimdal does not implement locked_out, however the Samba hdb
backend does, and needs this checked before passwords (for bad
password lockout), not after in kdc_check_access().
Signed-off-by: Gary Lockyer <gary@catalyst.net.nz>
=> Align locked out account behaviour with Windows

lib/gssapi/Makefile.am, lib/gssapi/NTMakefile, lib/gssapi/spnego/context_storage.c, lib/gssapi/spnego/context_stubs.c, lib/gssapi/spnego/negoex_ctx.c, lib/gssapi/spnego/negoex_util.c, lib/gssapi/spnego/spnego_locl.h
Support for exporting partially established acceptor context tokens. With this, an acceptor can send the initiator an encrypted state cookie containing the exported context token.
(The concrete mechanism, of course, must either require a single round trip or support partial context export itself. Kerberos and GSS EAP would work, but Kerberos with `GSS_C_DCE_STYLE` would not, as currently implemented.)
Partial context export is not permitted for initiators.
=> gss: allow partial accept context export in SPNEGO

lib/gssapi/mech/gss_mech_switch.c
This function became used outside the protection of
HAVE_DLOPEN (which Samba sets) with:
commit 5966c00701d9045fb5440a0d15c14a02cfd99f01
Author: Luke Howard <lukeh@padl.com>
Date:   Sun Aug 8 10:34:28 2021 +1000
gss: add gss_mg_name_to_oid internal API
Add a new function for future internal use, gss_mg_name_to_oid(), which takes
either a dot-separated OID or a "short" mechanism name (such as
"sanon-x25519"), and returns a mechanism OID.
=> Allow _gss_string_to_oid() without HAVE_DLOPEN

kdc/kdc.h, kdc/kerberos5.c
This is to match the Windows KDC behaviour, optionally.
Samba will use this mode, as Samba has tests that show
the difference and is keen for bug-for-bug/byte-for-byte
rather than strict RFC compliance where there is a
reasonable choice.
The behaviour was changed in:
commit de1f37a6aadb35fdce3254528d89bdac23fb120b
Author: Luke Howard <lukeh@padl.com>
Date:   Mon Jan 7 15:45:36 2019 +1100
kdc: omit default salt from PA-ETYPE-INFO[2]
If the salt for the AS-REP client key matches the default password salt for the
client principal in the AS-REQ, then it can be omitted from the PA-ETYPE-INFO,
PA-ETYPE-INFO2 (RFC4120) as the client will assume the default salt in its
absence.
=> Allow KDC to always return the salt in the PA-ETYPE-INFO[2]

kuser/kinit.c, lib/hx509/cms.c, lib/hx509/hx509.h, lib/hx509/libhx509-exports.def, lib/hx509/version-script.map, lib/krb5/init_creds_pw.c, lib/krb5/krb5_locl.h, lib/krb5/libkrb5-exports.def.in, lib/krb5/pkinit.c, lib/krb5/version-script.map
Add the ` --pk-anon-fast-armor` option to kinit, which acquires a temporary anonymous PKINIT TGT to use as a FAST armor key.  The KDC certificate is not authenticated, per RFC 6113 5.4.1.1.
=> kuser: --fast-armor-anon-pkinit option for kinit

lib/gssapi/gss-token.c
e.g., OpenBSD does not provide this header.
=> Only #include <malloc.h> if it is available.

cf/Makefile.am.common
If clang-format is not available, AC_CHECK_PROG sets CLANG_FORMAT=no,
not empty string. This results in an error at build time for those
without clang-format installed. Instead check if the program is
executable.
=> Check CLANG_FORMAT is executable.

lib/asn1/asn1parse.y, lib/com_err/parse.y, lib/sl/slc-lex.l, lib/sl/slc.h
To comply with the latest POSIX standard, in Yacc compatibility mode
(options `-y`/`--yacc`) Bison now generates prototypes for yyerror and
yylex.  In some situations, this is breaking compatibility: if the user
has already declared these functions but with some differences (e.g., to
declare them as static, or to use specific attributes), the generated
parser will fail to compile.  To disable these prototypes, #define yyerror
(to `yyerror`), and likewise for yylex.
refer: https://git.savannah.gnu.org/cgit/bison.git/tree/NEWS
GNU Bison 3.8
in addition update `yyerror` to match the templated function with `const`
Reference #830 
tested with both 7.7.0 and master.
=> yyerror: update to POSIX standard

lib/krb5/krb5.h, lib/krb5/krbhst.c
Add a new krbhst type, KRB5_KRBHST_TKTBRIDGEAP to krb5_krbhst_init_flags(), that looks for the DNS SRV record kerberos-tkt-bridge. This is to support a new PADL project.
=> krb5: KRB5_KRBHST_TKTBRIDGEAP

lib/krb5/get_cred.c, tests/kdc/check-kdc.in
Fix for #816, turns out there was one more place that needed changing, as the tests show they both needed.
=> krb5: skip cache check in S4U2Proxy requests

lib/asn1/gen.c
roken is important to manage the correct selection of include files, ensure availability of error constants, and on Windows to manage the memory allocation routines
=> asn1_gen: use roken in generated source files

lib/asn1/der.c, lib/asn1/der_cmp.c, lib/asn1/der_copy.c, lib/asn1/der_format.c, lib/asn1/der_free.c, lib/asn1/der_length.c, lib/asn1/der_print.c, lib/asn1/der_put.c, lib/asn1/extra.c, lib/asn1/heim_asn1.h, lib/asn1/oid_resolution.c
The calling convention for all exported libasn1 functions must be ASN1CALL.   On Windows, ASN1CALL is _stdcall and without it its _cdecl.   Calling a _cdecl function with -stdcall convention results in the ESP register not being preserved properly.  The asn1 tests crash when compiled with /RTCs.
=> Fix calling convention for libasn1

configure.ac, lib/wind/Makefile.am
=> Fix #696 - Find python as part of the configure process

kdc/windc_plugin.h, lib/krb5/krb5-plugin.7, lib/krb5/locate_plugin.h, lib/krb5/send_to_kdc_plugin.h, lib/krb5/test_plugin.c
The plugin interfaces were originally implemented for use on
Unix where KRB5_CALLCONV, HEIM_CALLCONV and similar are defined
as nothing.  However, on 32-bit Windows the calling convention
matters and executing a __stdcall function through a __cdecl
function pointer will result in failures.
This change updates the krb5plugin_windc, krb5plugin_service_locate,
krb5plugin_send_to_kdc plugins to specify the KRB5_CALLCONV for
functions.   This brings the plugins into compliance with the
heim_plugin_common interface requirement that init() and fini()
use the platform specified HEIM_CALLCONV.
The krb5-plugin(7) man page is updated and the lib/krb5/test_plugin
test is also fixed.
With this change all tests pass on 32-bit Windows.
Change-Id: Ic9d2e1285c9c179e3898dc9d071ed092bcddc406
=> plugin interface functions must specify calling convention

kdc/krb5tgs.c
krb5tgs.c: In function ‘_kdc_tgs_rep’:
krb5tgs.c:1785:25: warning: ‘header_key’ may be used uninitialized in this function [-Wmaybe-uninitialized]
1785 |       &tkey_check->key, &tkey_check->key, tgt, &kdc_issued, &mspac);
|                         ^~~~~~~~~~~~~~~~
krb5tgs.c:2302:10: note: ‘header_key’ was declared here
2302 |     Key *header_key;
|          ^~~~~~~~~~
On Ubuntu 20.04 in a default Heimdal build with
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
The compiler doesn't trust that *header_key = tkey; is always
executed in tgs_parse_request() for ret == 0.
=> kdc: Fix ‘header_key’ may be used uninitialized in this function

kcm/cache.c
'uuid' is seen as an 'unsigned char*', thus '*uuid' is an 'unsigned char' where size is 1.
This solves a problem where two KCM ccaches's uuid have the same first byte hides each other.
What we observe:
* A user cannot discover tickets with (klist -l) but can access it with it's name
* The 'rpc.gssd' daemon is doing the same kind of pattern but using GSS calls (gss_acquire_cred)
What GDB told us:
* The 'kcm_ccache_get_uuids' is okay, all ccache are really present
* The 'kcm_ccache_resolve_by_uuid' is buggy, it only compare the first byte of each uuid.
Which may be the same as the one we're seeking. Selected ccache that will be, most probably, filtered-out afterward with a call to 'kcm_access'.
This leads to 'KRB5_FCC_NOFILE' errors while the uuid is correct.
Similar calls may be present. …
=> Revert "KCM wrong size memcmp"

lib/krb5/get_cred.c
The reply structure was not being zero-initialised in all cases, leading to crashes or possible heap corruption on error paths when we later freed it.
=> Initialise KDC reply

lib/krb5/pac.c
BUG: https://bugzilla.samba.org/show_bug.cgi?id=14642
Signed-off-by: Joseph Sutton <josephsutton@catalyst.net.nz>
Reviewed-by: Andrew Bartlett <abartlet@samba.org>
(cherry picked from Samba commit 28a5a586c8e9cd155d676dcfcb81a2587ace99d1)
=> s4/heimdal/lib/krb5/pac.c: Align PAC buffers to match Windows

README.fast, kdc/fast.c, kdc/kdc-tester.c, kdc/kdc_locl.h, kdc/kerberos5.c, kdc/krb5tgs.c, kdc/pkinit.c, kdc/windc.c, kuser/kinit.c, lib/asn1/krb5.asn1, lib/base/heim_err.et, lib/base/heimbasepriv.h, lib/gss_preauth/pa_client.c, lib/gss_preauth/pa_common.c, lib/krb5/deprecated.c, lib/krb5/fast.c, lib/krb5/get_cred.c, lib/krb5/init_creds_pw.c, lib/krb5/krb5_locl.h, lib/krb5/krbhst.c, lib/krb5/libkrb5-exports.def.in, lib/krb5/send_to_kdc.c, lib/krb5/version-script.map
This PR extends #796 with a merge of Apple's Heimdal open source drop 597.121.1.
Clearly it would have been better to build GSS pre-authentication on top of this, but, here we are. I would suggest reviewing and integrating #796 and #797 first.
The tests pass.
There is a lot of churn but, I have minimised it somewhat by not aggressively integrating some of the Apple features (e.g. completely rewritten TGS client). I am in the process of carefully comparing with the original to check for regressions.
The advantages of integrating this are:
- support for PA-ENC-CHALLENGE
- FAST reply key strengthening
- FAST support in TGS-REQ path (including for errors which the Apple code did not implement), both in libkrb5 and KDC
- refactored pre-authentication client that makes adding new mechanisms …
=> Import AS/TGS client from Apple Heimdal-597.121.1

lib/asn1/template.c
Previously, if left==right==A1_HEADER_LEN(tos), this would read past the end of the template array. Now we treat [left, right) as a half-open interval and no longer try to read from 'right'.
=> asn1: Fix binary search off-by-one read

kdc/fast.c
This variable was not being freed on all error paths.
=> kdc: Fix leak

lib/krb5/libkrb5-exports.def.in, lib/krb5/pac.c, lib/krb5/test_pac.c, lib/krb5/version-script.map, tests/plugin/windc.c
This lets us call it from Samba.
=> heimdal: Make _krb5_pac_get_kdc_checksum_info() into a global function

kdc/kdc_locl.h, kdc/kerberos5.c, kdc/krb5tgs.c, kdc/windc.c, kdc/windc_plugin.h, tests/plugin/windc.c
Samba includes the user's long-term credentials (encrypted in the AS reply key) to allow legacy authentication protocols such as NTLM to work even if the pre-authentication mechanism replaced the reply key (as PKINIT does).
Samba also needs to know whether the client explicitly requested a PAC be included (or excluded), in order to defer PAC exclusion until a service ticket is issued (thereby avoiding a name binding attack if the user is renamed between TGT and service ticket issuance).
References:
https://bugzilla.samba.org/show_bug.cgi?id=11441
https://bugzilla.samba.org/show_bug.cgi?id=14561
Closes: #864
Original authors:
- Joseph Sutton <josephsutton@catalyst.net.nz>
- Andrew Bartlett <abartlet@samba.org>
- Stefan Metzmacher <metze@samba.org>
=> kdc: update PAC hooks for Samba

kdc/fast.c, lib/krb5/fast.c, lib/krb5/libkrb5-exports.def.in, lib/krb5/version-script.map
This is required for compound identity.
=> kdc: Add support for explicit armoring from MS-KILE

kdc/krb5tgs.c
This matches Windows behaviour and the RFC6113 specification.
=> kdc: Check FAST authdata in ticket rather than in request body

kdc/kerberos5.c
Don't keep trying keys for encrypted-challenge if one decrypts but fails to verify. This also enables a KRB5KRB_AP_ERR_SKEW error to be returned to the client.
=> kdc: Don't keep trying keys for encrypted-challenge

kdc/kerberos5.c
Instead of always advertising PADATA-ENCRYPTED-CHALLENGE, we only advertise it if FAST is in use.
We also check configuration options to only advertise PADATA-ENC-TIMESTAMP if it will be accepted based on whether FAST is currently in use. This permits the non-RFC behaviour required to avoid breaking earlier Heimdal clients.
This incorporates changes from Apple Heimdal-597.140.2.
=> kdc: Don't advertise padata types that will not be accepted

kdc/default_config.c, kdc/kdc.h, kdc/krb5tgs.c
This allows Heimdal to match AD behaviour, when configured,
for the behaviour after Microsoft's CVE-2021-42287 when
PacRequestorEnforcement is set to 2.
Samba BUG: https://bugzilla.samba.org/show_bug.cgi?id=14686
REF: https://support.microsoft.com/en-au/topic/kb5008380-authentication-updates-cve-2021-42287-9dafac11-e0d0-4cb8-959a-143bd0201041
Signed-off-by: Joseph Sutton <josephsutton@catalyst.net.nz>
Reviewed-by: Andrew Bartlett <abartlet@samba.org>
[abarlet@samba.org based on Samba commit
756934f14cc87dc1adfd9315672ae5d49cb24d95
and f7a2fef8f49a86f63c3dc2f6a2d7d979fb53238a]
This will aid in #891 by introducing the required flag.
=> Samba CVE-2020-25719 kdc: Require PAC to be present

kdc/krb5tgs.c, lib/hdb/hdb.h
This proposes the patches that were made to Samba to address the November 2021 Security issues 
See https://www.samba.org/samba/security/CVE-2020-25719.html
We made changes to our (older) copy of Heimdal to address these issues and @josephsutton1 has now forward-ported those to modern Heimdal. 
(I've written the new longer commit messages)
=> Upstream Heimdal-side helpers for Samba's Nov 2021 security release

kdc/krb5tgs.c
If the 'require_pac' option is not set, we should not require a PAC in this situation.
=> kdc: Optionally allow missing additional ticket PAC for user-to-user

kdc/kerberos5.c, lib/hdb/hdb.h
From a commit by @metze-samba and myself in Samba's lorikeet-heimdal repo.  
We need more information in our auditing hooks for Samba to fill in it's internal audit logs with.   A common helper function was added to make this maintainable.
@metze-samba I dropped to TODO on this as I think is well baked now.
=> Pass extra info to hdb_auth_status()

kdc/krb5tgs.c
This is an import of an older Samba commit, updated over time in our lorikeet-heimdal tree we would like to get upstream if possible.
The AD-behaviour regression was introduced by upstream commit:
378f34b4be9865ed3949918fba8d2dd877b395c0
Signed-off-by: Isaac Boukris <iboukris@gmail.com>
[abartlet@samba.org Similar to Samba commit a9e6119ca0c2a78ef314c3162122539ee834aa04
but made conditional on server->entry.flags.force_canonicalize to
allow upstream submission]
=> tgs-rep: always return canonical realm even if canonicalize falg is not set, same as Windows.

kcm/config.c, kdc/config.c, kdc/kerberos5.c, kdc/krb5tgs.c, kuser/klist.c, lib/hx509/cert.c, lib/hx509/hxtool.c, lib/hx509/ks_p11.c, lib/roken/parse_bytes-test.c, lib/roken/parse_bytes.c, lib/roken/parse_bytes.h, lib/roken/parse_time.c, lib/roken/parse_time.h, lib/roken/parse_units.c, lib/roken/parse_units.h
Another patch by @josephsutton1:
If a function calls unparse_flags() to convert a KDCOptions value into a
string when the 'validate' flag is set, KDCOptions2int() will return 1
<< 31, which becomes −2147483648 when converted to a 32-bit signed
integer. Since the loop in unparse_something() only runs as long as its
input is greater than zero, this will result in nothing being printed to
the buffer. Changing unparse_flags() to take an int64_t avoids this
behaviour, at least until a 64th flag bit is added. We also return an
error value of -1 from unparse_something() if it receives a negative
value.
However, the callers are not checking the result from unparse_flags()
and would still have attempted to log these uninitialised bytes. Modify
some of these callers so that they perform this …
=> Fix up lib/roken parse/unparse functions

kdc/fast.c, kdc/kdc_locl.h, kdc/kerberos5.c, kdc/krb5tgs.c, lib/asn1/krb5.asn1, tests/kdc/check-fast.in
08e0305b introduced a patch to validate armor ticket PACs, but required that the armor client principal was in the local realm (as it did not allow _kdc_db_fetch() to fail).
Allwo cross-realm FAST armor clients by using the same logic to look up the client principal as the TGS itself does, i.e. use db_fetch_client() which ignores HDB_ERR_NOT_FOUND_HERE.
=> kdc: allow cross-realm FAST armor TGT

kdc/fast.c
Avoid a crash if verifying the armor ticket PAC fails.
=> kdc: Fix armor ticket PAC checking

kdc/altsecid_gss_preauth_authorizer.c, kdc/gss_preauth.c, kdc/gss_preauth_authorizer_plugin.h, kdc/kdc.h, kdc/kdc_locl.h, kdc/kerberos5.c, kdc/krb5tgs.c, kdc/pkinit.c, kdc/windc.c, kdc/windc_plugin.h, tests/plugin/windc.c
Encapsulate as much state as possible in `astgs_request_t`, with a view to eventually migrating the KDC to a table-driven architecture. In the interim, use a single `astgs_request_t` argument for pre- and post-hook plugins, e.g.:
```c
static krb5_error_code KRB5_CALLCONV
client_access(void *ctx, astgs_request_t r)
{
krb5_warnx(r->context, "client_access");
return 0;
}
static krb5_error_code KRB5_CALLCONV
finalize_reply(void *ctx, astgs_request_t r)
{
krb5_warnx(r->context, "finalize_reply");
return 0;
}
```
The `astgs_request_t` structure is separated into a public and private component, depending on whether we are building the KDC or not.
=> Make part of astgs_request_t public

kdc/kerberos5.c
Return `KRB5KDC_ERR_C_PRINCIPAL_UNKNOWN`, not `HDB_ERR_NOENTRY`, if a client principal could not be found during pre-authentication.
This fixes a regression introduced with synthetic principals in 00358252d3.
=> kdc: return KRB5KDC_ERR_C_PRINCIPAL_UNKNOWN (PA)

lib/asn1/krb5.asn1, lib/gssapi/Makefile.am, lib/gssapi/gssapi/gssapi.h, lib/gssapi/gssapi/gssapi_krb5.h, lib/gssapi/krb5/external.c, lib/gssapi/krb5/import_name.c, lib/gssapi/krb5/name_attrs.c, lib/gssapi/libgssapi-exports.def, lib/gssapi/mech/gss_import_name.c, lib/gssapi/test_names.c, lib/gssapi/version-script.map, lib/krb5/asn1_glue.c, lib/krb5/libkrb5-exports.def.in, lib/krb5/rd_req.c, lib/krb5/ticket.c, lib/krb5/version-script.map
`gss_get_name_attribute()`, `gss_inquire_name()`, `gss_display_name_ext()`, `gss_export_name_composite()`, and import of `GSS_C_NT_COMPOSITE_EXPORT` name tokens is included.
Missing functionality: `gss_set_name_attribute()` and `gss_delete_name_attribute()`.  Also, no plugin system is included at this time (a plugin would allow for additional attributes / prefixes, mappings/lookups, and/or local policy).
Attributes:
- `urn:mspac:` (same as MIT) (`XXX` missing are the URNs for the specific buffers)
- `urn:ietf:kerberos:nameattr-...`:
- attributes of all Kerberos names:
- `realm` (the realm of the name)
- `ncomp` (the number of components of the name)
- `ncomp#<digit>` (the corresponding component of the name)
- attributes of names from established security contexts:
- `canonical-name` (the …
=> Name Attributes

lib/gssapi/Makefile.am, lib/gssapi/krb5/name_attrs.c, lib/gssapi/test_context.c, lib/krb5/libkrb5-exports.def.in, lib/krb5/pac.c, lib/krb5/version-script.map
Expose PAC info buffers using naming attributes prefixed with `urn:mspac:`, aligned with MIT.
=> gss: expose PAC info buffers under urn:mspac:

cf/db.m4, lib/roken/ndbm_wrap.c
The prior inclusion of DB6 checks within the tree was incomplete.   The db6/db.h header was tested for and used in some places but the test for db_create() within libdb-6 if present did not exist.   
The roken ndbm-wrap functionality was also unaware of DB6.
=> complete support for DB6

include/config.h.w32, kdc/Makefile.am, kdc/NTMakefile, kdc/altsecid_gss_preauth_authorizer.c, kdc/bx509d.c, kdc/ca.c, kdc/csr_authorizer.c, kdc/default_config.c, kdc/gss_preauth.c, kdc/gss_preauth_authorizer_plugin.h, kdc/httpkadmind.c, kdc/kdc-plugin.c, kdc/kdc.h, kdc/kdc_locl.h, kdc/kerberos5.c, kdc/libkdc-exports.def, kdc/log.c, kdc/misc.c, kdc/pkinit.c, kdc/process.c, kdc/set_dbinfo.c, kdc/token_validator.c, kdc/version-script.map, lib/base/heimbase-svc.h, tests/plugin/kdc_test_plugin.c
Add a heim_dict_t to the KDC request structure for use by pre-authentication mechanisms and plugins.
=> add attribute dictionary to kdc_request_t

appveyor.yml, include/config.h.w32, lib/asn1/NTMakefile, lib/asn1/gen.c, lib/asn1/gen_template.c, lib/gssapi/NTMakefile, lib/hdb/NTMakefile, lib/roken/roken.h.in, lib/roken/strtoll.c, lib/roken/strtoull.c, packages/windows/installer/NTMakefile, packages/windows/installer/heimdal-installer.wxs, windows/NTMakefile.sdk, windows/NTMakefile.w32
Permit building with Windows 10 SDK and Visual Studio 2015 through 2019
Ensure that LIB_ASN1 is defined by all compiled source files that might be linked to generated ASN1 sources.  Doing this correctly prevents many linker warnings complaining about a library object referencing an internal DATA object via an import.
Build a static runtime version of libasn1.lib named libasn1_s.lib.   This is needed by thirdparty components that require the ASN1 library but cannot link to a dynamic runtime.
When casting an integer constant to `(void *)` use an intermediate cast to `(uintptr_t)` to prevent warnings about a smaller signed integer being extended to a larger unsigned pointer type.
=> win10sdk and asn1 build improvements

lib/asn1/krb5.asn1, lib/gssapi/Makefile.am, lib/gssapi/krb5/external.c, lib/gssapi/krb5/init_sec_context.c, lib/gssapi/krb5/name_attrs.c, lib/gssapi/test_context.c, lib/krb5/libkrb5-exports.def.in, lib/krb5/version-script.map, tests/gss/check-context.in
The implementation of GSS name attributes for Kerberos (or any mechanism
with more than a tiny handful) is much nicer as a table-driven
implementation.
=> gss: Make krb5 name attrs table-driven

lib/gssapi/krb5/accept_sec_context.c
We have a Heimdal special where when the acceptor sends back an error
token for clock skew or ticket-not-yet-valid errors then the acceptor
application will get GSS_S_CONTINUE_NEEDED from gss_accept_sec_context()
so that the initiator may retry with the same context.
But we were retaining the auth_context, which means that when the
initiator does send a new token, the acceptor leaks memory because
krb5_verify_ap_req2() doesn't clean up the auth_context on reuse.  The
end result is that we leak a lot in those cases.
=> gsskrb5: Do not leak authenticator on retry

kdc/Makefile.am, kdc/NTMakefile, kdc/headers.h, kdc/kdc-audit.h, kdc/kerberos5.c, lib/hdb/hdb.h
Move KDC auth event macro definitions out of `hdb.h` and into a new KDC header, `kdc-audit.h`.
=> kdc: move auth event definitions into KDC header

lib/hcrypto/evp.c
The hc_evp_md_init, hc_evp_md_update and hc_evp_md_final typedefs
are defined as functions returning an int, but null_Init, null_Update
and null_Final are defined as void, and cast with the typedef when
assigned to the function vector.
This might result in some uninitialized value being returned to the
caller, if some of them make use of the return value.  It also causes
warnings if the -Wcast-function-type warning is enabled.
Change the type to in to match the typedef, and return 1 (success).
=> hcrypto: Fix return type for null_Init, null_Update and null_Final

lib/roken/roken.h.in, lib/roken/strftime.c
ec866e635e3c80d6de6bca4f49865a1b2b1213c2
("Windows 10 SDK build fixes") introduced CPP macros
timezone -> _timezone
tzname   -> _tzname
but these names are common and the macros rewrite too much.
Change-Id: Ic813bff842124595fd3d86761cee6dcea4ae44e4
=> roken: do not define 'timezone' and 'tzname'

lib/gssapi/mech/mech_locl.h
If included roken.h should be immediately following config.h.
Doing so ensures that all platform specific headers are
included in the proper order and avoids unnecessary includes
of headers managed by roken.h.
=> gssapi/mech: mech_locl.h roken.h must be included earlier

lib/hcrypto/engine.c
Must dlclose(handle) before returning even if 'engine' is
returned to caller.
=> lib/hcrypto: ENGINE_by_dso do not leak handle

kadmin/rpc.c, lib/base/data.c, lib/gssapi/mech/gss_import_name.c, lib/gssapi/mech/gss_krb5.c, lib/hdb/print.c, lib/kadm5/ipropd_master.c
When an unsigned char is shifted << 24 bits its type will be
promoted to signed 32-bits.   If the value is then assigned to
an unsigned 64-bit value sign extension will occur.
Prevent the unwanted sign extension by explicitly casting the
value to unsigned long before shifting.
=> prevent unintended sign extension errors

kdc/altsecid_gss_preauth_authorizer.c, kdc/kerberos5.c, kdc/libkdc-exports.def, kdc/process.c, kdc/version-script.map, tests/plugin/kdc_test_plugin.c
We will use the kdc_ rather than `krb5_kdc_` prefix for new public APIs exported from `libkdc`. Amend the recently introduced `request_{get,set,copy,delete}_attribute` APIs to conform.
=> kdc: remove krb5_ prefix for KDC attribute functions

kdc/fast.c, kdc/kerberos5.c, kdc/krb5tgs.c, kdc/kx509.c, kdc/libkdc-exports.def, kdc/mssfu.c, kdc/process.c, kdc/version-script.map
Samba plugins will need to use auditing API without including krb5-private.h, so make the auditing APIs public.
Essentially this patch is `s/_kdc_audit/kdc_audit/` except for `_kdc_audit_trail`.
=> kdc: make auditing API public

configure.ac, include/config.h.w32, kadmin/rpc.c, lib/asn1/gen_copy.c, lib/asn1/gen_free.c, lib/gssapi/krb5/init_sec_context.c, lib/hcrypto/libtommath/etc/tune.c, lib/hx509/cert.c, lib/hx509/cms.c, lib/hx509/file.c, lib/hx509/req.c, lib/kafs/rxkad_kdf.c, lib/krb5/send_to_kdc.c, lib/ntlm/digest.c, lib/roken/base32.c, lib/roken/dirent-test.c, lib/roken/fnmatch.c, lib/roken/getuserinfo.c, lib/roken/snprintf.c, lib/roken/strftime.c, lib/roken/strptime.c, lib/wind/utf8.c
The pseudo keyword 'fallthrough' is defined such that case statement
blocks must end with any of these keywords:
* break;
* fallthrough;
* continue;
* goto <label>;
* return [expression];
*
*  gcc: https://gcc.gnu.org/onlinedocs/gcc/Statement-Attributes.html#Statement-Attributes
The macro is defined either as
__attribute__((__fallthrough__))
or as
do {} while (0)  /* fallthrough */
not including the semicolon.
This change implements the Linux kernel style and updates several locations
where "/*fallthrough*/ and /* FALLTHROUGH */ were not previously replaced.
Externally imported code such as libedit, libtommath and sqlite are
restored to their unaltered state.
Change-Id: I69db8167b0d5884f55d96d72de3059a0235a1ba3
=> Follow the Linux kernel's lead on "fallthrough"

lib/asn1/der_copy.c, lib/asn1/der_get.c, lib/asn1/der_put.c, lib/gssapi/krb5/arcfour.c, lib/krb5/pac.c, lib/krb5/store_emem.c
The definitions of memcpy(), memmove(), and memset() state that
the behaviour is undefined if any of the pointer arguments are
NULL, and some compilers are known to make use of this to
optimise away existing NULL checks in the source.
Change-Id: I489bc256e3eac7ff41d91becb0b43aba73dbb3f9
Link: https://www.imperialviolet.org/2016/06/26/nonnull.html
=> assert non-NULL ptrs before calling mem funcs

kdc/fast.c, kdc/kdc-plugin.c, kdc/kdc-plugin.h, kdc/kerberos5.c, kdc/krb5tgs.c, kdc/mssfu.c
This is more consistent and allows the pac hooks to be more flexible.
=> kdc-plugin: also pass astgs_request_t to the pac related functions

kdc/fast.c, kdc/kdc-accessors.h, kdc/kdc_locl.h, kdc/krb5tgs.c, kdc/libkdc-exports.def, kdc/version-script.map
_kdc_fast_check_armor_pac() already checks the PAC of the armor,
but it should also remember it if it's an TGS-REQ with explicit armor.
This will allow the kdc pac hooks to generate a compound identity PAC
with PAC_TYPE_DEVICE_INFO.
=> kdc: provide kdc_request_get_explicit_armor_{clientdb,client,pac}()

lib/krb5/pac.c
PAC_TYPE_CLIENT_CLAIMS_INFO and PAC_TYPE_DEVICE_CLAIMS_INFO are
of zero length unless any claims are actually defined.
=> lib/krb5: re-allow data->length == 0 in krb5_pac_add_buffer()

lib/krb5/pac.c
This allows these functions to be used with PACs obtained from KDC accessor functions such as kdc_request_get_pac().
=> lib/krb5: Make parameters to PAC functions 'const'

kdc/kdc-plugin.c, kdc/libkdc-exports.def, kdc/version-script.map
Since plugins no longer have a way of accessing the 'ek' member of the request structure, this function provides a way for a plugin to add encrypted padata to the response.
=> kdc: Add function to add encrypted padata

lib/roken/timeval.c
INTxx_MIN plus a positive integer of the same type will always be negative, and so the result will always compare less than a positive integer. Fix this check so that we produce the correct result when adding two negative time_t values.
=> roken: Fix time_t overflow checking

doc/setup.texi, kadmin/kadmin.1, lib/hdb/common.c, lib/hdb/hdb.asn1, lib/hdb/hdb.opt, lib/hdb/keytab.c, tests/gss/krb5.conf.in, tests/kdc/check-kdc.in, tests/kdc/check-referral.in
At some point we had "hard HDB entry aliases" working, and I broke it when I needed to add something like soft aliases -- I made all aliases soft.  This PR has a fix.
The fix is to distinguish soft and hard aliases by convention.
- Soft aliases are aliases of `WELLKNOWN/REFERRALS/TARGET@${some_realm}` or , `WELLKNOWN/REFERRALS/TARGET/...@${some_realm}`  where the realm is the realm to issue referrals to when a client asks for a ticket for an alias of such a principal.
The second form is needed because there is a limit to how many aliases an HDB entry can have due to the signed 16-bit "TL-data" length limit imposed by the `kadm5` APIs and MIT kadmin protocol.
- Hard aliases are all others.
`kadmin`/`kadmind`/`httpkadmind`/`kadm5` will not care about the alias type distinction -- we push it …
=> Hard and soft HDB entry aliases

kadmin/check.c, kadmin/get.c, kadmin/kadmin-commands.in, kadmin/kadmin_locl.h, kadmin/kadmind.c, kadmin/server.c, kadmin/util.c, lib/kadm5/ad.c, lib/kadm5/common_glue.c, lib/kadm5/context_s.c, lib/kadm5/destroy_s.c, lib/kadm5/get_princs_c.c, lib/kadm5/get_princs_s.c, lib/kadm5/init_c.c, lib/kadm5/init_s.c, lib/kadm5/libkadm5srv-exports.def, lib/kadm5/private.h, lib/kadm5/version-script-client.map, lib/kadm5/version-script.map, tests/kdc/check-kadmin.in
I've had it with `kadmin list` being slow when there are _many_ principals in a database.
This PR adds a `kadm5_iter_principals()` function that uses a callback rather than gathering all [matching] principals into an array in memory.
This PR also adds a variation on the Heimdal kadmin protocol's `LIST` operation that is correspondingly online, implements it in `kadmind`, and makes the `kadmin` client use it.
Lastly, there is a test, which tests listing an HDB w/ 20 principal in chunk sizes of 7 (three chunks), 10 (two chunks), and 50 (one chunk).  Testing listing of an HDB w/ zero principals is... hard and pointless, so no need.
=> kadmin online listing

lib/ipc/server.c
The `inmsg` field of the client structure is malloc/realloc'ed in `handle_read` but never free'ed in `maybe_close`.
Seems like Apple already fixed that with this.
=> KCM: Memory leak in `handle_read`

kcm/config.c, kcm/events.c, kcm/kcm_locl.h
Add --no-automatic-renewal option to disable automatic TGT renewal.
Renewal can also be disabled by setting automatic_renewal to false
in the [kcm] section of krb5.conf.
=> kcm: Allow disabling automatic TGT renewal

kdc/digest-service.c, kdc/digest.c, lib/gssapi/krb5/8003.c, lib/gssapi/krb5/arcfour.c, lib/gssapi/netlogon/crypto.c, lib/gssapi/ntlm/crypto.c, lib/hcrypto/des.c, lib/hcrypto/dh.c, lib/hcrypto/dsa.c, lib/hcrypto/engine.c, lib/hcrypto/evp-openssl.c, lib/hcrypto/evp.c, lib/hcrypto/hmac.c, lib/hcrypto/md2.c, lib/hcrypto/passwd_dlg.c, lib/hcrypto/rand-fortuna.c, lib/hcrypto/rc2.c, lib/hcrypto/rsa.c, lib/ntlm/ntlm.c, lib/otp/otp_verify.c
Using memset_s() ensures that sensitive memory is cleared, and constant-time memory comparisons help to prevent timing attacks.
=> Use memset_s() and constant-time memory comparisons

lib/roken/copyhostent.c, lib/roken/freeaddrinfo.c, lib/roken/freehostent.c, lib/roken/getaddrinfo.c, lib/roken/getipnodebyaddr.c, lib/roken/getipnodebyname.c, lib/roken/getnameinfo.c, lib/roken/roken.h.in
Roken functions rk_copyhostent(), rk_freeaddrinfo(), rk_freehostent()
rk_getaddrinfo(), rk_getipnodebyaddr(),  rk_getipnodebyname(), and
rk_getnameinfo() should never be built without the "rk_" prefix.  Doing
so overrides the system provided functions of the same name when they
exist.
(cherry picked from commit 7b3a99323632677d4255532049cc5a1031d8f706)
=> roken: do not override system network address functions

configure.ac, include/config.h.w32, kadmin/rpc.c, kuser/kinit.c, lib/asn1/gen_copy.c, lib/asn1/gen_free.c, lib/gssapi/krb5/init_sec_context.c, lib/hx509/cert.c, lib/hx509/cms.c, lib/hx509/file.c, lib/hx509/req.c, lib/ipc/server.c, lib/kafs/rxkad_kdf.c, lib/krb5/send_to_kdc.c, lib/ntlm/digest.c, lib/roken/base32.c, lib/roken/dirent-test.c, lib/roken/fnmatch.c, lib/roken/getaddrinfo.c, lib/roken/getuserinfo.c, lib/roken/snprintf.c, lib/roken/strftime.c, lib/roken/strptime.c, lib/wind/utf8.c
Apple clang version 14.0.0 (clang-1400.0.17.3.1) fails the build because stds.h defines `fallthrough` as a macro which is then expanded when base.h evaluates
The macOS SDK defines `DISPATCH_FALLTHROUGH` as the macro instead of `fallthrough`.
This change replaces the use of `fallthrough` in the tree with `HEIM_FALLTHROUGH` and updates the declaration in configure logic to define `HEIM_FALLTHROUGH` based upon existing definitions (if any) of `fallthrough` or `DISPATCH_FALLTHROUGH`.
=> fallthrough logic breaks on macOS 14 SDK with clang 14

doc/Makefile.am, lib/gssapi/Makefile.am, lib/hdb/Makefile.am
`git` version of `GNU make` added `make --shuffle` mode in https://savannah.gnu.org/bugs/index.php?62100.
This mode managed to find a few missing build-time dependencies in `heimdal`:
hdb: add missing build dependency on "hdb-protos.h"
doc: add dependency on vars.texi
gssapi: add dependency on gkrb5_err.h
Before the change `make --shuffle -j16` did not survive more than 2 consecutive builds for me.
After the change I saw 15 successful consecutive builds until I gave up.
=> make --shuffle build fixes

kdc/default_config.c, kdc/fast.c, kdc/kdc_locl.h, kdc/krb5tgs.c, lib/krb5/krb5.conf.5
This makes it possible to disable fast if needed,
which is very good for regression tests.
Samba disables this in a few test environments with this
option.
BUG: https://bugzilla.samba.org/show_bug.cgi?id=15002
BUG: https://bugzilla.samba.org/show_bug.cgi?id=15005
Signed-off-by: Stefan Metzmacher <metze@samba.org>
=> kdc: add enable_fast option (enabled by default)

admin/Makefile.am, admin/add.c, admin/copy.c, admin/get.c, admin/ktutil-commands.in, admin/ktutil.1, admin/list.c, kadmin/NTMakefile, kdc/Makefile.am, kdc/bx509d.8, kdc/bx509d.c, kdc/httpkadmind.8, kdc/httpkadmind.c, kuser/Makefile.am, kuser/klist.c, lib/base/heimbase.h, lib/base/heimbasepriv.h, lib/base/json.c, lib/base/string.c, lib/base/test_base.c, lib/base/version-script.map, lib/kadm5/iprop.8, lib/kadm5/ipropd_slave.c, lib/krb5/keytab.c, tests/kdc/check-bx509.in, tests/kdc/check-httpkadmind.in
This PR:
- fixes usage of libmicrohttpd ("MHD"), specifically as to handling of POSTs with non-zero-length bodies, and cleanup of request context
- adds a `/get-tgts` batch end-point to `kdc/bx509d.c`
- updates the man pages `kdc/httpkadmind.8` and `kdc/bx509d.8`
- adds commentary about how MHD is used
The `/get-tgt` end-point that's already in `master` is for getting a TGT given some other credential.
The `/get-tgts` end-point is the same, but for multiple principals at a time -- a batched version of `/get-tgt`.
These HTTPS services can now handle POST form data and multi-part too, where those are treated the same as URI q-param key/value pairs.  Internally, the main MHD request handler callback (`route()`) takes care of most everything, including authentication, CSRF protection, and …
=> Add `/get-tgts` batch end-point for "prestash" service; also fix POST support in bx509d and httpkadmind

lib/asn1/gen_free.c, lib/krb5/store-int.c
On systems where 'unsigned long' is 32-bits and the 'size' parameter is set to 8 and the bytes are:
0x78 0x00 0x00 0x00 0x00 0x00 0x00 0x00
When 'i' becomes 4 'v' will be 0 again. As 'unsigned long' is only able to hold 4 bytes.
Change the type of 'v' from 'unsigned long' to 'uint64_t' which matches the type of the output parameter 'value'.
Signed-off-by: Stefan Metzmacher <metze@samba.org>
Reviewed-by: Ralph Boehme <slow@samba.org>
CVE: CVE-2022-42898
Samba-BUG: https://bugzilla.samba.org/show_bug.cgi?id=15203
=> lib/krb5: fix _krb5_get_int64 on 32-bit systems

kdc/krb5tgs.c, kdc/pkinit.c, kuser/kinit.c, lib/asn1/krb5.opt, lib/ipc/server.c
Use --preserve-binary=KDC-REQ-BODY option to ASN.1 compiler to avoid re-encoding KDC-REQ-BODYs for verification in GSS preauth, TGS and PKINIT.
[abartlet@samba.org adapted from Heimdal commit
ebfd48e40a1b61bf5a6b8d00fe5c581e24652b6e
by removing references to FAST and GSS-pre-auth.
This fixes the Windows 11 22H2 issue with TGS-REQ
as seen at https:github.com/heimdal/heimdal/issues/1011 and so
removes the knownfail file for this test]
FIXES: 1011
=> Fix for 1011 from Samba

lib/krb5/store-int.c
On systems where 'unsigned long' is 32-bits and the 'size' parameter is set to 8 and the bytes are:
0x78 0x00 0x00 0x00 0x00 0x00 0x00 0x00
When 'i' becomes 4 'v' will be 0 again. As 'unsigned long' is only able to hold 4 bytes.
Change the type of 'v' from 'unsigned long' to 'uint64_t' which matches the type of the output parameter 'value'.
(cherry picked from commit 9d1bfab9882d0aa14ae0981e6667c93db93ffc5d)
Signed-off-by: Stefan Metzmacher <metze@samba.org>
Reviewed-by: Ralph Boehme <slow@samba.org>
CVE: CVE-2022-42898
Samba-BUG: https://bugzilla.samba.org/show_bug.cgi?id=15203
=> [7.7.1] lib/krb5: fix _krb5_get_int64 on 32-bit systems

lib/krb5/store-int.c
On systems where 'unsigned long' is 32-bits and the 'size' parameter is set to 8 and the bytes are:
0x78 0x00 0x00 0x00 0x00 0x00 0x00 0x00
When 'i' becomes 4 'v' will be 0 again. As 'unsigned long' is only able to hold 4 bytes.
Change the type of 'v' from 'unsigned long' to 'uint64_t' which matches the type of the output parameter 'value'.
(cherry picked from commit https://github.com/heimdal/heimdal/commit/9d1bfab9882d0aa14ae0981e6667c93db93ffc5d)
Signed-off-by: Stefan Metzmacher [metze@samba.org](mailto:metze@samba.org)
Reviewed-by: Ralph Boehme [slow@samba.org](mailto:slow@samba.org)
CVE: CVE-2022-42898
Samba-BUG: https://bugzilla.samba.org/show_bug.cgi?id=15203
=> [7.8.0] lib/krb5: fix _krb5_get_int64 on 32-bit systems

lib/krb5/pac.c
48 byte memory leak from krb5_pac_parse() each time pac_header_size() fails.
(cherry picked from commit 02f12fc746341f54a514e9e17bc7d315b91129e8)
=> lib/krb5: krb5_pac_parse mem leak if pac_header_size failure

include/config.h.w32, lib/krb5/krb5_locl.h
__func__ is a C99 standard variable but it is not available on MSVC _MSC_VER < 1900.  
Define __func__ as __FUNCTION__ on older MSVC so that the general define can be removed.
=> Older MSVC does not provide __func__

kdc/gss_preauth.c, lib/asn1/gen_encode.c, lib/asn1/gen_template.c, lib/base/log.c, lib/krb5/ticket.c
Format string fixes that fail in the Samba build on a 32-bit machine
Signed-off-by: Volker Lendecke <vl@samba.org>
=> heimdal: Fix the 32-bit build on FreeBSD

kdc/kerberos5.c
If the function fails, we should not issue a ticket missing the PAC.
=> kdc: Check generate_pac() return code

kdc/kerberos5.c
This is needed when a service provides support for newer entry.etypes
without having a key for that encryption type yet.
It is triggered by svc_use_strongest_session_key=TRUE
=> kdc: add missing enctype = p[i] assignments to _kdc_find_etype()

lib/base/json.c
While the local stack pointers could be thought of as "only" numbers that are not invalidated by the memory they point at being freed, any use of the pointer after the free is undefined and so warned about (at best).
gcc version 12.2.1 20220819 (Red Hat 12.2.1-1) (GCC)
=> lib/base: Avoid compiler warning about use-after-free on Fedora 36

kdc/csr_authorizer_plugin.h, kdc/gss_preauth_authorizer_plugin.h, kdc/kdc-plugin.h, kdc/token_validator_plugin.h, lib/base/common_plugin.h, lib/base/heimbase-svc.h, lib/base/plugin.c, lib/hdb/hdb-ldap.c, lib/hdb/hdb.c, lib/hdb/hdb.h, lib/hdb/test_namespace.c, lib/kadm5/kadm5-hook.h, lib/krb5/an2ln_plugin.h, lib/krb5/db_plugin.h, lib/krb5/kuserok_plugin.h, lib/krb5/locate_plugin.h, lib/krb5/send_to_kdc_plugin.h
Heimdal's HDB plugin interface, and hence Samba's KDC that depends upon it, doesn't work on 32-bit builds due to structure fields being arranged in the wrong order. This problem presents itself in the form of segmentation faults on 32-bit systems, but goes unnoticed on 64-bit builds thanks to extra structure padding absorbing the errant fields.
This commit reorders the HDB plugin structure fields to prevent crashes and introduces a common macro to ensure every plugin presents a consistent interface.
=> Fix HDB plugin crashes on 32-bit systems

lib/krb5/fast.c, lib/krb5/init_creds_pw.c, lib/krb5/pkinit.c
NOTE: commit 1cdc9d5f3cff0288846c29c35ee91b6056a2e2bb
"krb5: export krb5_init_creds_step()" exported
krb5_init_creds_step() the first time, but that's
not in any released version, so it should be fine
to fix up the prototype in order to make the
function actually useful for external callers.
All the "lib/krb5: remove unused krb5_krbhst_info argument of" commits are
not strictly required, but they show that the last commit
"lib/krb5: remove dead code from pk_verify_host()"
actually removed dead code. If the logic
in pk_verify_host() should be kept,
a krb5_krbhst_info should be passed in though any useful
way, but passing it to krb5_init_creds_step() is clearly not
the correct way. Maybe a new krb5_init_creds_set_*() function.
=> Make krb5_init_creds_step() usable at all and match the MIT version of it

kdc/krb5tgs.c, kdc/pkinit.c, lib/asn1/krb5.opt
Use --preserve-binary=KDC-REQ-BODY option to ASN.1 compiler to avoid re-encoding KDC-REQ-BODYs for verification in GSS preauth, TGS and PKINIT.
[abartlet@samba.org adapted from Heimdal commit
ebfd48e40a1b61bf5a6b8d00fe5c581e24652b6e
by removing references to FAST and GSS-pre-auth.
This fixes the Windows 11 22H2 issue with TGS-REQ
as seen at https:github.com/heimdal/heimdal/issues/1011 and so
removes the knownfail file for this test]
FIXES: 1011
(cherry picked from commit 4cd3926e14eca91ca10a9ec87200c8bd717b66e4)
=> kdc: avoid re-encoding KDC-REQ-BODY

lib/base/heimbase-atomics.h
commit acad7be65ec3dd504470f8f8a4d6f353718e93bc
Author: Luke Howard <lukeh@padl.com>
Date:   Wed Dec 9 11:00:11 2015 +1100
base: Solaris and AIX atomic increment/exchange
Implement heim_base_atomic_XXX and heim_base_exchange_pointer
for Solaris and AIX. (AIX not tested.)
introduced untested support for aix, untested code is broken code...
So this is tested on AIX 7 now.
=> Heimdal aix atomics

lib/roken/mkdtemp.c
Both the len and the index was decremented, which made the exit condition (template[len - i] == 'X') trigger before it should. Fixes solaris10 where mkdtemp is not available.
=> roken/mkdtemp.c: fix incorrect indexing

lib/gssapi/krb5/8003.c, lib/gssapi/krb5/arcfour.c, lib/gssapi/krb5/cfx.c, lib/gssapi/krb5/inquire_sec_context_by_oid.c, lib/gssapi/krb5/prf.c, lib/gssapi/krb5/unwrap.c, lib/gssapi/krb5/verify_mic.c, lib/gssapi/mech/gss_krb5.c, lib/gssapi/mech/gss_utils.c, lib/gssapi/mech/utils.h
Replace calls to `_gsskrb5_{en,de}code...()` with mechglue equivalents.
=> gss: use mechglue instead of gsskrb5 encoders

lib/asn1/template.c, lib/base/heimbase-atomics.h, lib/gssapi/spnego/context_storage.c
roken: provide a getline implementation from libedit if needed
spnego/context_storage: undef sc_flags (for hpux)
heimdal/asn1: do not throw error when trying to allocate 0 bytes of memory
heimbase-atomics.h: replace heim_base_atomic_barrier with syntax valid noop
=> Some portability fixes

lib/krb5/crypto.c
decrypt_internal_derived(), decrypt_internal_enc_then_cksum(), decrypt_internal(), and decrypt_internal_special() execute the following pattern where 'p' is an allocation of size 'len'
l = len - n
memmove(p, p + n, l);
result->data = realloc(p, l);
if (result->data == NULL && l != 0) {
free(p);
return krb5_enomem(context);
}
result->length = l;
which when compiled by gcc 13.0.1-0.12.fc38 or gcc-13.0.1-0.13.fc39 generates the following warning
warning: pointer 'p' may be used after 'realloc' [-Wuse-after-free]
The C language specification indicates that it is only safe to free() the pointer passed to realloc() if errno is set to ENOMEM.  Yet the warning is generated by the following pattern
l = len - n
memmove(p, p + n, l);
errno = 0;
result->data = realloc(p, l);
if (result->data == NULL …
=> krb5: crypto.c avoid realloc to trim memory allocation

cf/crypto.m4
Check for OpenSSL features while LDFLAGS and CFLAGS are set with the paths provided in the configure command line. This allows detecting a non-default OpenSSL's version correctly, such as on FreeBSD with one of the OpenSSL 3.0 ports.
=> cf: Honour OpenSSL library and include paths

kdc/bx509d.c, kdc/ipc_csr_authorizer.c, kdc/test_csr_authorizer.c, lib/asn1/asn1_print.c, lib/asn1/gen.c, lib/base/config_file.c, lib/gssapi/mech/gss_mech_switch.c, lib/gssapi/netlogon/import_name.c, lib/hcrypto/test_dh.c, lib/hdb/hdb.c, lib/hx509/file.c, lib/kadm5/marshall.c, lib/krb5/cache.c, lib/krb5/principal.c, lib/roken/rtbl.c
Excluded: libtomath and libedit files, most of which appear to be testing or example code not involved in production, and which are derived from an upstream that should perhaps have patches submitted upstream instead.
fix https://github.com/heimdal/heimdal/issues/1111
=> Fix ctype.h misuse.

kdc/kerberos5.c
It confuses clients if the kdc announces support for a pa-type, e.g. KRB5_PADATA_FX_FAST and later ignore/reject it
=> only announce enabled pa types

kdc/fast.c, kdc/krb5tgs.c, lib/hdb/hdb.h
This is useful to be able to tell whether a principal is being looked up just to verify a FAST armor ticket, which lets the HDB plugin avoid some unnecessary work.
=> hdb: Add armor principal flag

kcm/config.c, kdc/config.c, lib/asn1/check-gen.c, lib/hx509/hxtool.c, lib/roken/parse_bytes-test.c, lib/roken/parse_bytes.c, lib/roken/parse_bytes.h
On 32 bit systems, sizeof(ssize_t) and sizeof(unsigned long aka UL) is 32 bits which is not able to hold the value of a terabyte.
=> roken/parse_bytes: fix test for >= terabyte units on 32 bit systems

kadmin/check.c
This helps with certain automation tools, such as ansible, that usually expect failure to be visible in stderr.
Other minor changes:
* replace "doesn't" with "does not" to keep messages consistent and avoid escaping quotes in grep, etc.
* add newlines
=> kadmin/check: move error messages to stderr

lib/asn1/Makefile.am, lib/hx509/Makefile.am
Bison must generate this unsolicited, but BSD yacc does not.
The makefiles for lib/com_err and lib/sl already did this; this change just adds it to lib/asn1 and lib/hx509 too.
fix https://github.com/heimdal/heimdal/issues/1100
=> Pass -d to yacc(1) so it generates the header file.

lib/asn1/Makefile.am, lib/com_err/Makefile.am, lib/sl/Makefile.am
YFLAGS and LFLAGS are reserved for the user to set, not for makefiles to set:
https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html
fix https://github.com/heimdal/heimdal/issues/1171
=> Makefile.am: Set AM_YFLAGS and AM_LFLAGS, not YFLAGS or LFLAGS.

kadmin/kadmin.1, kadmin/util.c, kdc/default_config.c, kdc/httpkadmind.c, kdc/kdc_locl.h, kdc/misc.c, lib/hdb/hdb.asn1, lib/kadm5/admin.h, lib/kadm5/ent_setup.c, lib/kadm5/get_s.c, lib/krb5/krb5.conf.5, tests/kdc/check-kdc.in
One site needs to disable PACs altogether for service tickets, but might need to enabled them on a case by case basis.
With these patches we now default to using PACs, which can be turned off on a per-service principal basis with the `no-auth-data-reqd` flag, or one can disable PACs for all but root `krbtgt`s and then enable PACs on a case by case basis (including cross-realm `krbtgt`s) with the new `auth-data-reqd` HDB entry flag.
If both flags get set, then you end up with `no-auth-data-reqd` set and `auth-data-reqd` reset:
=> Add HDB entry auth-data-reqd flag

cf/make-proto.pl, configure.ac
This patch removes the need for an external package.
Ported from
https://github.com/openwrt/packages/blob/master/net/samba4/patches/105-perl-json-pp.patch https://github.com/openwrt/packages/commit/402f4ba4eff65b80a9deaa6085256112bec4d67b#diff-208d4e0345c9d29fbec23d6f655ba794afd3052f5cb8dd73944db72ce81b847b
=> Use perl module JSON:PP, part of core, instead of JSON package

admin/add.c
Under C99, Sec 6.2.4, paragraph 2:
> The value of a pointer becomes indeterminate when the object it points to reaches the end of its lifetime.
'Indeterminate' (3.17.2) includes a trap representation, and any reference to a trap representation is undefined behaviour.  Thus, after realloc(res, ...) succeeds, any reference to res (or p) is undefined behaviour.
So, instead of using `p - res` after res has been freed, use the existing name for the value we know it has now: len.  (We could also use alloced because p == end in this branch, and end = res + alloced, and p = res + len.  Of course, we would have to move it up a line to before we update alloced to have a different value.)
fix https://github.com/heimdal/heimdal/issues/1164
=> ktutil: Avoid even arithmetic on res after realloc(res, ...).

lib/hx509/ca.c, lib/hx509/hxtool-commands.in, lib/hx509/hxtool.c, lib/hx509/libhx509-exports.def, lib/hx509/req.c, lib/hx509/test_req.in, lib/hx509/version-script.map, tests/kdc/check-bx509.in
bx509d / kx509 will reject CSRs that have an `extReq` w/ a `BasicConstraints`, but it should really either ignore it or reject `cA` requests.
As well it should ignore non-critical unknown `Extension`s in `extReq`.
This comes up with CSRs issued by Dell iDRACs, which include a non-critical `BasicConstraints` extension w/ `cA` set to false.  Nothing in RFCs 2985 (PKCS#9) or 2986 (PKCS#10) says anything about CSRs having to include `BasicConstraints` or not, but evidently some do so we need to support that.
(defaults to not issuing CA certs anyways)
`libhx509` changes:
- when parsing a CSR check for `BasicConstraints` in the `extReq`
- count critical and non-critical unsupported `extReq`s separately
- add `hx509_request_set_cA()` to mark a CSR as wanting a CA cert (this has an argument for …
=> hx509: Add support for CSRs w/ BasicConstraints

lib/kadm5/bump_pw_expire.c, lib/krb5/krb5.conf.5, lib/roken/parse_time-test.c
when [kadmin] password_lifetime is set to 0, it should clear the time rather than making the freshly-changed password expire immediately
=> kadm5: allow setting password_lifetime to 0 to clear

lib/krb5/krb5.conf.5
If multiple valid CRLs are specified for a particular issuer, only the first will be checked. The documentation didn’t really hint at this.
=> krb5: Clarify documentation for ‘pkinit_revoke’ parameter

lib/krb5/send_to_kdc.c
Instead of freeing host->ai on return from submit_request in the http_proxy path, stash the proxy's ai in another member host->freeai which will be freed when host is freed.
Assumption: All hosts created in submit_request cease to be used before any of them are freed, so it's safe to pick one host to hang the proxy's ai on and free the ai when that host is freed.
fix https://github.com/heimdal/heimdal/issues/1205
=> krb5: Fix use-after-free when debug is enabled with http_proxy.

configure.ac
heimdal uses 8-byte (64-bits) atomic operations for a while now (ie in lib/krb5/krcache.c). however some platforms (ie i386, i486, ARM < 7) don't support them natively and need to be linked against libatomic in order to implement functionallity from <stdatomic.h>.
if the header was found check 64-bit atomics work without any additional libraries. if not try to add linking with libatomic. if that fails as well fallback to -DHEIM_BASE_ATOMICS_FALLBACK
no change for platfroms without <stdatomic.h>
Fixes: #1186
=> cf: link libatomic if needed

appl/gssmask/gssmask.c, appl/test/auditdns.c, lib/kadm5/ipropd_slave.c, lib/krb5/krbhst.c, lib/krb5/send_to_kdc.c, lib/krb5/sock_principal.c, lib/roken/roken-common.h
1. Unconditionally pass NI_NUMERICHOST|NI_NUMERICSERV|NI_NUMERICSCOPE to most getnameinfo calls.
2. Predicate the remaining call, in krb5_sock_to_principal, on block_dns = no.
3. Add getnameinfo and gethostbyaddr stubs to auditdns.c to help check for leaks.
While here: tidy up the minor issues left over from https://github.com/heimdal/heimdal/pull/1213 (https://github.com/heimdal/heimdal/pull/1213#pullrequestreview-1811770450, https://github.com/heimdal/heimdal/pull/1213#pullrequestreview-1811778956, and a harmless stray semicolon).
fix https://github.com/heimdal/heimdal/issues/1214
=> Prevent network leaks of reverse DNS lookups with [libdefaults] block_dns = yes.

kdc/Makefile.am
when microhttpd is present, bx509d does not build because the automake-emitted makefile uses the wrong name for the per-target CPPFLAGS variables. Correct the Makefile.am file in the kdc subdir to work when microhttpd is installed
=> kdc: per-target CPPFLAGS do not have an _AM in the variable name

kdc/default_config.c
commit 4d48b172ab06692e9f23b24c120b61465f43c94b ("add pkinit configration for btmm") introduced automatic configuration of the 'pkinit_kdc_identity' and 'pkinit_kdc_friendly_name' on macOS but also modified the default for the 'enable_pkinit' setting such that pkinit is enabled on all __APPLE__ platforms overriding the [kdc] enable-pkinit setting obtained from the configuration.
This change modifies the enable-pkinit behavior on __APPLE__ platforms to match those on every other platform.
=> kdc: APPLE disable enable-pkinit by default as documented

lib/gssapi/krb5/arcfour.c, lib/gssapi/krb5/cfx.c, lib/gssapi/krb5/sequence.c, lib/gssapi/krb5/unwrap.c, lib/gssapi/krb5/verify_mic.c
A couple of fixes for issues with checking sequence ordering in GSSAPI
=> Gssapi sequence fixes

lib/krb5/fast.c, lib/krb5/mcache.c
Fix two clock skew related issues:
- failing TGS-REP due to a clock skew error is reported as "missing FAST" to the caller
- implement/fix clock skew offset adjustment in the memory cache, this ensures a TGS-REQ uses the clock skew time offset from the AS-REP
=> Clock skew fixes

lib/gssapi/krb5/8003.c, lib/gssapi/krb5/init_sec_context.c, lib/gssapi/test_context.c, lib/krb5/build_auth.c, lib/krb5/mk_req_ext.c, tests/gss/check-context.in
Allow an application to provide GSS_C_CHANNEL_BOUND_FLAG on the client side and
force KERB_AP_OPTIONS_CBT.
See https://github.com/krb5/krb5/pull/1329
=> Allow GSS_C_CHANNEL_BOUND_FLAG on the client

lib/krb5/fast.c
if using armoring service.
(The source and destination is exchanged in the call, which makes the "value" part (fxarmor.armor_value) not filled up, so the armored ticket request will not be encrypted correctly and will fail.)
=> krb5/fast.c: fix copying source/dest for copy_KrbFastArmor

lib/otp/otp_db.c
include ndbm.h if HAVE_DB_NDBM is defined to avoid implicit function declarations.
otp_db.c:76:9: error: call to undeclared function 'dbm_open'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
ret = dbm_open (OTP_DB, O_RDWR | O_CREAT, 0600);
^
=> otp: prevent implicit function declarations if HAVE_DB_NDBM

lib/krb5/salt-des.c
If crypt() is unavailable, do not register support for afs-string-to-key
=> afs string to key requires crypt

lib/krb5/krbhst.c
Fix inverted logic introduced by #1155 that results in DNS not working if `block_dns` is `false`, rather than `true`.
=> krb5: Correct inverted conditions

appl/test/auditdns.c
The 'restrict' keyword was introduced in C99 and provides a hint to the compiler that can be used to better optimized code.  The 'restrict' keyword results in build failures on some platforms.  Since auditdns.c is a test and optimization is unimportant for successful completion, elimination of the 'restrict' keyword is an acceptable change to permit successful completion of the build.
auditdns.c:101:37: error: expected ‘;’, ‘,’ or ‘)’ before ‘hints’
const struct addrinfo *restrict hints,
^
auditdns.c:409:45: error: expected ‘;’, ‘,’ or ‘)’ before ‘sa’
getnameinfo(const struct sockaddr *restrict sa, socklen_t salen,
Observed with gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44).
^
=> appl/tests: auditdns eliminate use of 'restrict' keyword

lib/krb5/krbhst.c
I believe the code we have in Heimdal to deal with TLD name collisions is not quite right because the `target` of a DNS `SRV` RR has to have a trailing `'.'`.  This should fix it, though... we have no test.
=> krb5: Fix DNS SRV name collision handling

cf/resolv.m4
When building for Apple operating systems rk_dns_lookup() must use dns_search() instead of res_search().  Although res_search() is available, it only issues queries using the /etc/resolv.conf configuration.  Whereas dns_search() will issue the query against alternate resolver configurations such as those created by VPN services.
=> cf: dns_search test requires resolv library

lib/base/config_file.c
CFReadStreamCreateWithFile() will fail due to the current working directory being invalid or inaccessible.  Instead of returning ENOMEM which is a fatal error, return EACCESS which permits the configuration parsing to continue without the plist.
For example, on macOS, if the cwd is in /afs and the user's tokens have expired, then krb5_init_context() fails with ENOMEM (12).
user@MacBookAir user % ~/src/heimdal/kuser/heimtools klist
shell-init: error retrieving current directory: \
getcwd: cannot access parent directories: Permission denied
chdir: error retrieving current directory: \
getcwd: cannot access parent directories: Permission denied
heimtools: krb5_init_context failed: 12
With this change krb5_init_context() succeeds.  It is important to note that the plist …
=> macOS: permit krb5_init_context to succeed if current working directory is inaccessible or invalid

lib/gssapi/krb5/8003.c
Windows clients forget GSS_C_MUTUAL_FLAG in some situations where they use GSS_C_DCE_STYLE, in the assumption that GSS_C_MUTUAL_FLAG is implied.
Both Windows and MIT as server already imply GSS_C_MUTUAL_FLAG when GSS_C_DCE_STYLE is used.
BUG: https://bugzilla.samba.org/show_bug.cgi?id=15740
=> gsskrb5: let GSS_C_DCE_STYLE imply GSS_C_MUTUAL_FLAG as acceptor
