heimdal/heimdal

doc/standardisation/rfc6806.txt, kdc/fast.c, kdc/kerberos5.c, kdc/krb5tgs.c, kdc/misc.c, lib/gssapi/krb5/aeap.c, lib/gssapi/krb5/arcfour.c, lib/gssapi/krb5/decapsulate.c, lib/hdb/hdb_err.et, lib/krb5/init_creds_pw.c, lib/krb5/libkrb5-exports.def.in, lib/krb5/mk_error.c, lib/krb5/pac.c, lib/krb5/version-script.map, lib/ntlm/Makefile.am
These patches were posted to heimdal-discuss by metze, and there were no objections there.
=> Samba Cross-realm support patches from metze

lib/krb5/mcache.c
BUG: https://bugzilla.samba.org/show_bug.cgi?id=12369
Signed-off-by: Stefan Metzmacher metze@samba.org
Reviewed-by: Günther Deschner gd@samba.org
Reviewed-by: Uri Simchoni uri@samba.org
(Bases on Samba commit 2abc3710a8a63327a769ba0482c553ed274b2113)
=> lib/krb5: destroy a memory ccache on reinit

po/heim_com_err-1750206208/de.po, po/heim_com_err-1765328384/de.po, po/heim_com_err-1980176640/de.po, po/heim_com_err-969269760/de.po, po/heim_com_err569856/de.po, po/heimdal_krb5/de.po, po/heimdal_kuser/de.po
Hi,
this german translation files are new. I will update the error messages soon
Kind regards,
Chris
=> German translation

tests/kdc/check-iprop.in
=> Skip mdb_stat test when the command is not available

configure.ac, tests/kdc/Makefile.am, tests/kdc/check-keys.in
=> Don't do AFS string-to-key tests when feature is disabled

tools/Makefile.am, tools/krb5-config.in
This should resolve #237, please confirm
=> In krb5-config resolve rpath_flag at build-time

lib/sqlite/sqlite3.h
Keep SQLite up to date in master.
=> Update SQLite to 3.17.0

appl/su/su.c, cf/roken-frag.m4, lib/gssapi/ntlm/init_sec_context.c, lib/gssapi/ntlm/kdc.c, lib/gssapi/spnego/accept_sec_context.c, lib/hcrypto/evp-pkcs11.c, lib/hcrypto/rand.c, lib/hx509/softp11.c, lib/kafs/afssys.c, lib/krb5/cache.c, lib/krb5/config_file.c, lib/krb5/context.c, lib/krb5/expand_path.c, lib/krb5/keytab.c, lib/roken/Makefile.am, lib/roken/NTMakefile, lib/roken/getauxval.c, lib/roken/getauxval.h, lib/roken/issuid.c, lib/roken/roken.h.in, lib/roken/secure_getenv.c, lib/roken/secure_getenv.h, lib/roken/test-auxval.c, lib/roken/version-script.map, lib/roken/write_pid.c
=> Add secure_getenv()

tests/kdc/check-iprop.in
(cherry picked from commit 4052b286bbbf6cc7822071ee8c38f64047a176f0)
=> Fix missing wait_for in check-iprop

kdc/pkinit.c
Please merge these fix, so we can backport it into Samba's copy of Heimdal.
Thanks!
=> kdc: fix dh->q allocation check in get_dh_param()

lib/libedit/src/sys.h
Only include sys/types.h if we actually have it.
=> Fixes https://github.com/heimdal/heimdal/issues/308

lib/hdb/hdb-ldap.c
Heimdal will refuse to create new entries when an entry already exists even
if said entry has no kerberos info and is a new entry.
This patch fixes this issue by allowing object modifications even if the
flags disallow them when we are inserting a new principal on the database.
Signed-off-by: Francisco Blas Izquierdo Riera (klondike) klondike@gentoo.org
=> Allow LDAP modifications for entry creation

kdc/connect.c
Use PF_UNIX instead of PF_LOCAL
=> Fixes https://github.com/heimdal/heimdal/issues/310

kadmin/cpw.c
=> kadmin/cpw: Add error code on password missmatch

lib/krb5/crypto-arcfour.c, lib/krb5/crypto.c, lib/krb5/mit_glue.c
Please merge these fixes which are already in Samba's copy of heimdal.
Thanks!
=> Heimdal checksum fixes

kdc/connect.c
- Simplify child process creation rate limit by moving
select_sleep() to happen right after the parent fork().
- Consider child pid table slots to be empty if the pid is
non-positive, rather than just -1 or just 0.
- Log warnings should we ever spawn a child with no free
slot to track it, or reap a child that does not match
a tracked slot.
=> Further improve kdc child process management

lib/gssapi/ntlm/accept_sec_context.c, lib/krb5/context.c
free context etypes and ntlm ctx.
=> Ntlm context leak

lib/roken/gettimeofday.c
GetSystemTimeAsFileTime() has 16ms precision.
GetSystemTimePreciseAsFileTime() has <1ns precision but is only available
on Windows 8 or later.
This change dynamically loads GetSystemTimePreciseAsFileTime() if it is
available.
Change-Id: Ib9c616c01948384e6b256ac9b6023f1e39673613
=> roken: gettimeofday using GetSystemTimePreciseAsFileTime

lib/wind/gen-bidi.py, lib/wind/gen-combining.py, lib/wind/gen-errorlist.py, lib/wind/gen-map.py, lib/wind/gen-normalize.py, lib/wind/generate.py, lib/wind/stringprep.py
Samba aims to build with python3 in the near future, and this set of patches provides that support in the Heimdal code we have within our build system.
=> Partial Python3 compatability

tests/kdc/wait-kdc.sh
Fix output to be grammatically correct.
=> For issue#381

lib/hdb/common.c
This patch implements "hard" aliases where to the client an aliased principal is indistinguishable from an unaliased one: it's not required to request name canonicalization and the client is returned the name it asked for. (Note: you need to create a TGS alias, too.)
I've made this a runtime configurable option in this initial implementation: I'm being careful not to change the name canonicalization (NC) behavior as I don't want to break Samba (cc @abartlet). IIRC Windows always sets NC flag in the AS-REQ, so perhaps I'm being needlessly cautious, however there are a couple of edge cases:
- The MIT code always canonicalizes the client realm in the returned ticket (I recall implementing this based on observed Windows behavior). However, for hard aliases to work (where the client expects …
=> kdc: Support aliases for client principal initial ticket acquisition (#452)

lib/krb5/init_creds_pw.c
krb5: krb5_get_init_creds_opt_set_change_password_prompt incomplete (#322)
krb5_get_init_creds_opt_set_change_password_prompt() was being ignored by krb5_init_creds_step() which broke pam_krb5 tests. MIT doesn't handle password expiration within krb5_init_creds_step(), instead deferring to higher level functions such as krb5_get_init_creds_password(). However, Heimdal kinit uses krb5_init_creds_step() directly and thus requires this behaviour to be implemented to pass its own tests.
=> krb5: remove key expired handler from krb5_init_creds_step() (#322)

.travis.yml, configure.ac, include/Makefile.am, include/config.h.w32, lib/base/heimbase.h, lib/krb5/Makefile.am, lib/krb5/NTMakefile, lib/krb5/constants.c, lib/krb5/context.c, lib/krb5/k5e1_err.et, lib/krb5/krb5.h, lib/krb5/krb5_locl.h, lib/krb5/krcache.c, lib/krb5/libkrb5-exports.def.in, lib/krb5/test_cc.c, lib/krb5/version-script.map, packages/windows/sdk/NTMakefile
Initial revision for review, needs tests.
=> krb5: port MIT Linux keyring credentials cache (#166)

lib/ntlm/ntlm.c
It was 00 earlier, changed it to 0f(15). Also made the reserved field
before it 00 00 00 instead of 0f 00 00.
Issue #404
=> Fixed incorrect NTLM version.

include/config.h.w32, lib/gssapi/krb5/acquire_cred.c, lib/krb5/keytab.c, lib/krb5/krb5_locl.h, lib/krb5/libkrb5-exports.def.in, lib/krb5/verify_krb5_conf.c, lib/krb5/version-script.map
WIP for #383 – not sure if fix should be this simple?
=> gssapi: default client keytab (#383)

lib/gssapi/Makefile.am, lib/gssapi/NTMakefile, lib/gssapi/gssapi/gssapi.h, lib/gssapi/gssapi_mech.h, lib/gssapi/krb5/external.c, lib/gssapi/libgssapi-exports.def, lib/gssapi/mech/cred.c, lib/gssapi/mech/gss_get_neg_mechs.c, lib/gssapi/mech/gss_mech_switch.c, lib/gssapi/mech/gss_set_neg_mechs.c, lib/gssapi/netlogon/external.c, lib/gssapi/ntlm/external.c, lib/gssapi/spnego/cred_stubs.c, lib/gssapi/spnego/external.c, lib/gssapi/version-script.map
Untested
commit against lukeh/gss-cred-store
=> gss_set_neg_mechs (#495)

lib/gssapi/Makefile.am, lib/gssapi/NTMakefile, lib/gssapi/gssapi/gssapi_oid.h, lib/gssapi/mech/gss_oid.c, lib/gssapi/ntlm/accept_sec_context.c, lib/gssapi/ntlm/crypto.c, lib/gssapi/ntlm/external.c, lib/gssapi/ntlm/set_sec_context_option.c, lib/gssapi/oid.txt, lib/gssapi/spnego/accept_sec_context.c, lib/gssapi/spnego/compat.c, lib/gssapi/spnego/init_sec_context.c
=> gssapi: SPNEGO does not reset NTLM RC4 state (#509)

kdc/kerberos5.c
Heimdal's current behavior regarding the generation of PA-ETYPE-INFO2
and PA-ETYPE-INFO violates RFC4120 in two ways:
1. when generating responding both PA-ETYPE-INFO2 and PA-ETYPE-INFO
the hints returned in the inverse order: INFO then INFO2 instead
of INFO2 then INFO.
2. the determination that both PA-ETYPE-INFO2 and PA-ETYPE-INFO is
currently based upon the KDC selected enctype when it should be
determine based upon examining the entire enctype list specified
by the requesting client.
This change corrects the behavior to follow the RFC4120 guidance.
=> kdc: get_pa_etype_info_both comply with RFC4120

kdc/kerberos5.c, kdc/krb5tgs.c, lib/hdb/common.c
* generate default salts for entries missing them
* omit default salt from etype info
=> KDC salt fixes

lib/krb5/store_fd.c, lib/krb5/store_stdio.c, lib/krb5/test_store.c
Couple of optimisations of stdio krb5_storage and a couple of tests and increasing the consistency of truncate between backends a bit.
=> Storage stdio

kdc/kerberos5.c, kdc/krb5tgs.c, kdc/pkinit.c, kuser/kgetcred.1, kuser/kgetcred.c, kuser/kinit.1, kuser/kinit.c, kuser/kuser_locl.h, lib/krb5/get_cred.c, lib/krb5/krb5.h, lib/krb5/krb5_locl.h, lib/krb5/libkrb5-exports.def.in, lib/krb5/pkinit.c, lib/krb5/principal.c, lib/krb5/send_to_kdc.c, lib/krb5/ticket.c, lib/krb5/version-script.map, tests/kdc/check-kdc.in
Anonymous fixes up to but not including GSS_C_ANON_FLAG support
=> krb5 anonymous fixes (ex-GSS)

lib/krb5/send_to_kdc.c
Comment in the commit. It is a little naughty of me to re-use the fd to keep state in this way but it does avoid another variable in wait_ctx. I'm no wedded to it, though, we can decide to be cleaner.
=> Sendto kdc

kdc/krb5tgs.c, lib/krb5/init_creds_pw.c, lib/krb5/krb5_locl.h, lib/krb5/pkinit.c
[Samba CVE-2018-16860](https://www.samba.org/samba/security/CVE-2018-16860.html)
=> CVE-2018-16860 and PA-PKINIT-KX verification

lib/hcrypto/evp-pkcs11.c
Before committing to a PKCS#11 mechanism, check that it can provide the required encryption or digest services by validating the flags returned by C_GetMechanismInfo().
=> hcrypto-pkcs11: check mechanism flags

kdc/kerberos5.c, kdc/krb5tgs.c, kuser/klist.c, lib/krb5/init_creds.c, lib/krb5/krb5_locl.h, lib/krb5/pkinit.c
A few fixes from the lukeh/gss-anon branch that are not related to GSS_C_ANON_FLAG
=> Various fixes for master

.travis.yml
matches the file contents of 26048694d736aa844d2be0abc6bd82a1cf51cfef
Change-Id: Ic4b269abb20618824ed4ad9f68424167700d833b
=> .travis.yml: synchronize with master

configure.ac
=> Fix build for out-of-source objdir

lib/kadm5/ipropd_master.c
When the master sees a burst of updates (perhaps sustained), the
slaves "I_HAVE" messages can fall behind the version we've already
sent, and the unpatched code would retransmit already sent diffs!
This can result in substantial amplification (in a local test, 3000
ops turned into 427,000 ops).  Though the number of *messages* sent
was actually somewhat smaller, the ever growing message size
ultimately leads to failure.
=> Don't stutter in send_diffs

lib/kadm5/ipropd_master.c
(cherry picked from commit d383fd3b5677ed87090adb5cf68a03c8ea9f29f5)
=> Don't send diffs to slaves with not yet know version

configure.ac, include/config.h.w32, lib/kadm5/Makefile.am, lib/kadm5/get_s.c, lib/kadm5/ipropd_master.c, lib/kadm5/ipropd_slave.c, lib/kadm5/kadm5_locl.h, lib/kadm5/libkadm5srv-exports.def, lib/kadm5/log.c, lib/kadm5/test_pw_quality.c, lib/kadm5/version-script.map, lib/roken/net_write.c, tests/kdc/check-iprop.in
This can wait until we've reviewed and merged the master version. I omits the refactoring to make send_diffs() incremental as that is perhaps too much of a change for a stable release.
=> Async iprop for Heimdal 7.x

lib/asn1/oid_resolution.c, lib/asn1/rfc2459.asn1, lib/gssapi/Makefile.am, lib/gssapi/gss-token.1, lib/gssapi/gss-token.c, lib/hx509/cert.c, lib/hx509/hxtool.c, lib/hx509/sel.c, lib/roken/Makefile.am, lib/roken/base64.c, lib/roken/vis.c, lib/roken/vis.hin
=> Import gss-token, add rkvis

kuser/kx509.c, lib/krb5/kx509.c
Couple of quick bugs that I found in the kx509 code.
=> Kx509 bugs1

lib/hcrypto/evp-wincng.c, lib/roken/NTMakefile, lib/roken/rand.c, lib/roken/versionsupport.h
=> WinCNG reusable hash support

kdc/krb5tgs.c, tests/kdc/check-kdc.in
Samba advisory: https://www.samba.org/samba/security/CVE-2019-14870.html
=> CVE-2019-14870: Client attributes not checked in protocol-transition request (S4U2Self)

kdc/kx509.c, lib/base/log.c, lib/hdb/ndbm.c, lib/kadm5/randkey_c.c, lib/krb5/mk_cred.c
rebased to current master and without the errant hex_decode fix for kadmin/load
=> revised coverity fixes

admin/add.c, appl/otp/otp.c, kadmin/ank.c, kadmin/cpw.c, kadmin/stash.c, kdc/kstash.c, kpasswd/kpasswd.c, lib/hcrypto/ui.c, lib/hcrypto/ui.h
(cherry picked from commit 014f16883c7c911b2804fb081e885e0571528e85)
=> cherry pick libhcrypto: UI_UTIL_FLAG_VERIFY_SILENT

lib/gssapi/spnego/accept_sec_context.c, lib/gssapi/spnego/init_sec_context.c
Resolves issue #486 based on a patch by Nico Williams.
A GSS-API acceptor can return an error token to be sent to the initiator. Our SPNEGO implementation discarded these when sending a SPNEGO reject response. This patch fixes the SPNEGO acceptor to convey those in the SPNEGO response.
The SPNEGO initiator is also updated to not bail out early on receiving a SPNEGO reject response from the acceptor, but instead pass the response token (if any) to gss_init_sec_context(). A reject response with no response token will continue to return an error.
=> gss: pass mechanism error tokens through SPNEGO

.travis.yml, tests/gss/krb5.conf.in
Trying to reproduce the krb5.conf issue I had in PR #712 as a separate test.
=> krb5.conf include issue

lib/base/baselocl.h, lib/base/config_file.c, lib/base/context.c, lib/base/expand_path.c, lib/krb5/acache.c, lib/krb5/cache.c, lib/krb5/context.c, lib/krb5/krb5-v4compat.h, lib/krb5/krb5.h, lib/krb5/krb5_locl.h, lib/krb5/pkinit.c, lib/krb5/scache.c, lib/krb5/test_cc.c
Also, try to narrow down the nature of the Appveyor pacman failures.
=> Fix use of KRB5_USE_PATH_TOKENS, refactor a bit

.travis.yml, lib/hcrypto/rsa-ltm.c, lib/hcrypto/test_cipher.c, lib/roken/getaddrinfo-test.c, lib/roken/roken.h.in, lib/roken/test-mini_inetd.c
A few more warnings fixed and in one case we are able to remove a warning from the permitted list.
=> Fix more heimdal warnings

lib/libedit/configure.ac
Also search libtermcap.
Signed-off-by: Earl Chew <earl_chew@yahoo.com>
=> [libedit/configure.ac] Search libtermcap for tgetent

tests/kdc/check-kdc.in, tests/kdc/check-referral.in
=> Follow-up PAC related tests

kdc/fast.c, lib/asn1/krb5.asn1, lib/krb5/krb5_err.et
They were not previously being checked for.
=> kdc: Check for unsupported critical FAST options

kdc/fast.c, kdc/krb5tgs.c
Look up the client name of the armor TGT in the database, and check that the PAC is valid.
=> kdc: Check PAC of FAST armor tickets

appveyor.yml, include/config.h.w32, lib/roken/roken.h.in, lib/roken/strtoll.c, lib/roken/strtoull.c, packages/windows/installer/NTMakefile, packages/windows/installer/heimdal-installer.wxs, windows/NTMakefile.sdk, windows/NTMakefile.w32
Creating a PR to track Windows 10 build fixes
* update for Windows 10 SDK
* build without Win32.mak
=> Windows 10 SDK build fixes

kdc/kerberos5.c
We weren't checking for errors, and we weren't using the convience
SEQUENCE OF add_METHOD_DATA() and add_ETYPE_INFO() functions generated
by the ASN.1 compiler.  Using those utilities made get_pa_etype_info()
and make_etype_info_entry() sufficiently simpler that merging the two
makes for simpler, more readable code.
=> kdc: Rewrite get_pa_etype_info and set_salt_padata

windows/README.md
I recently did a complete build using Visual Studio 2019 and SDK 10.0.19041.0.
There was a bit of a learn cliff and I have tried to capture my experience in the attached patch stream to windows\README.md.
I am **not** proposing that this be accepted as is.  It is more there to inform a rewrite of this page some time (and to act as memo to myself when I next loop back through here)
=> Some notes on building with VC2019

kdc/kerberos5.c
If the function fails, we should not issue a ticket missing the PAC.
(cherry picked from commit 05e589d2473a1bd225b0fc4670c75ba24091644d) (cherry picked from commit d1e077c50b6b6e6108d70a0301b97f6904c45ca7)
=> kdc: Check generate_pac() return code

lib/asn1/asn1parse.y, lib/asn1/der.h, lib/asn1/gen.c, lib/asn1/symbol.h
A few patches to the JSON emitted by `asn1compile` that are useful for [ASN1CodingKit](https://github.com/PADL/ASN1CodingKit).
=> ASN.1 compiler patches for Swift ASN1CodingKit

lib/krb5/store_stdio.c
Observed this issue on solaris10, hpux, aix.
What happens is that an "fwrite following an fread" writes extra characters to the file (probably the read buffer), so the file becomes corrupt. The workaround I have found is to do a seek to the current position before the write. This patch fixes the unit test of store_stdio.
=> krb5/store_stdio.c: workaround for solaris10/hpux/aix fread/fwrite duplication

kdc/fast.c, kdc/kerberos5.c, kdc/krb5tgs.c, kdc/mssfu.c, kdc/pkinit.c, lib/krb5/changepw.c, lib/krb5/crypto.c, lib/krb5/deprecated.c, lib/krb5/init_creds.c
Just a collection of minor fixes that I had lying around.
=> Some miscellaneous fixes

appl/gssmask/gssmask.c, lib/hdb/hdb-mitdb.c
fix https://github.com/heimdal/heimdal/issues/1102
fix https://github.com/heimdal/heimdal/issues/1105
=> Fix some compiler warnings.

kuser/kinit.c
Tested on macOS Venture 13.4.  Not sure if this requires some compatibility ifdefs for older macOS.
fix https://github.com/heimdal/heimdal/issues/1168
=> kinit: Update SecKeychainFindGenericPassword to SecItemCopyMatching.

kdc/kerberos5.c, kdc/krb5tgs.c, kdc/pkinit.c, kuser/kinit.c, lib/base/json.c, lib/hdb/ext.c, lib/hx509/cert.c, lib/hx509/cms.c, lib/hx509/crypto-ec.c, lib/hx509/crypto.c, lib/hx509/hx509_err.et, lib/hx509/req.c, lib/hx509/revoke.c, lib/hx509/test_cms.in, lib/krb5/cache.c, lib/krb5/crypto.c, lib/krb5/digest.c, lib/krb5/init_creds_pw.c, lib/krb5/krb5_err.et, lib/krb5/pac.c, lib/krb5/pkinit.c, lib/krb5/store.c, lib/wind/utf8.c, po/heimdal_krb5/de.po, po/heimdal_krb5/heimdal_krb5.pot, po/heimdal_krb5/sv_SE.po
A few spelling fixes that I’ve accumulated from working on the KDC and X.509 areas of the codebase.
=> Fix code spelling

kdc/pkinit.c, kuser/kinit.c, lib/hcrypto/rsa-ltm.c, lib/hx509/ca.c, lib/hx509/cms.c, lib/krb5/crypto-evp.c, lib/roken/strerror.c, lib/wind/UnicodeData.py, lib/wind/gen-bidi.py, lib/wind/gen-combining.py, lib/wind/gen-errorlist.py, lib/wind/gen-map.py, lib/wind/gen-normalize.py, lib/wind/gen-punycode-examples.py, lib/wind/generate.py, lib/wind/rfc3454.py, lib/wind/rfc4518.py, lib/wind/stringprep.py, lib/wind/util.py
Some fixes and tidy-ups that I’ve managed to accumulate.
=> Miscellaneous fixes and tidy-ups

kdc/kerberos5.c, kdc/krb5tgs.c, kdc/pkinit.c, lib/krb5/init_creds_pw.c
A few more small changes that I hope should be fairly easy to accept into upstream Heimdal from Samba's lorikeet-heimdal fork
=> More simple fixes from samba

ChangeLog.2005, ChangeLog.2006, ChangeLog.2007, appl/dceutils/dfspag.exp, appl/dceutils/dpagaix.c, doc/setup.texi, lib/asn1/ChangeLog, lib/base/heimbase.h, lib/gssapi/mech/gss_compare_name.c, lib/gssapi/oid.txt, lib/hcrypto/libtommath/doc/bn.tex, lib/hx509/ChangeLog, lib/kadm5/ChangeLog, lib/kafs/ChangeLog, lib/kdfs/k5dfspag.c, lib/krb5/acache.c, lib/krb5/addr_families.c, lib/krb5/context.c, lib/krb5/dcache.c, lib/krb5/doxygen.c, lib/krb5/fcache.c, lib/krb5/get_cred.c, lib/krb5/get_for_creds.c, lib/krb5/kcm.c, lib/krb5/krbhst.c, lib/krb5/mcache.c, lib/krb5/scache.c, lib/krb5/store.c, lib/roken/dlfcn_w32.c, lib/wind/ChangeLog
Translated files in `/po` folder are not modified.
=> Fix spelling

cf/largefile.m4
Fixes https://github.com/heimdal/heimdal/issues/1201
=> cf/largefile.m4: Fix build with autoconf-2.72

lib/gssapi/Makefile.am, lib/krb5/Makefile.am, lib/roken/Makefile.am
This was needed to run checks in darwin@nixpkgs: https://github.com/NixOS/nixpkgs/pull/348370
=> Link tests with -lresolv that depend on it
